name = "firth"
version = "0.1.0"
defaultTargets = ["firthTest", "firthParserTest", "firthErasureTest", "firthStackEffectTest"]
testDriver = "firthTest"

[[lean_lib]]
name = "Firth"
srcDir = "src/interpreter"

[[lean_lib]]
name = "FirthElaborator"
srcDir = "src"
roots = ["elaborator.Firth.Parser", "elaborator.Firth.Erasure", "elaborator.Firth.StackEffect", "elaborator.FirthElaborator"]

[[lean_exe]]
name = "firthTest"
root = "FirthTest"
srcDir = "src/interpreter"

[[lean_exe]]
name = "firthParserTest"
root = "elaborator.FirthParserTest"
srcDir = "src"

[[lean_exe]]
name = "firthVmFixtures"
root = "FirthVmFixtures"
srcDir = "src/interpreter"

[[lean_exe]]
name = "firthErasureTest"
root = "elaborator.FirthErasureTest"
srcDir = "src"

[[lean_exe]]
name = "firthStackEffectTest"
root = "elaborator.FirthStackEffectTest"
srcDir = "src"
