import FirthReferenceRun

/-!
Generated by `lake exe firthExportLean` from `examples/inventory/allocator.firth`. Do not edit:
`python3 tools/loop/update_kernel_exports.py` regenerates it, and CI fails when
this file differs from what the elaborator produces from that source.

Each word's `body` is the erased kernel program the elaborator checked and the
compiler accepted, and `bodyDigest` is the `body_digest` of that program in the
VM image. `FirthExportsTest` lowers every `body` again and fails unless it
hashes to `bodyDigest`.

`dictionary`, `Firth.ReferenceRun.adapterGamma` and `defaultCosts` are exactly
what the reference runner executes these words with.
-/

namespace Firth.Exports.Inventory.Allocator
open Firth.Interpreter
open Firth.ReferenceRun

/-- SHA-256 of the source text these definitions were generated from. -/
def sourceDigest : String := "9479ea4e718cb11470d51c445b419a745824c23b2e24bdc431fe8fcf90dc6513"

namespace «quantities-in-range-from»

/-- The erased kernel program of `quantities-in-range-from`. -/
def body : Program :=
  .cons .dup <|
  .cons (.pick 2) <|
  .cons (.prim "seq-int.len") <|
  .cons (.prim "<") <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.lit (.int 0)) <|
    .cons (.pick 2) <|
    .cons (.pick 2) <|
    .cons (.prim "seq-int.at") <|
    .cons (.prim "<") <|
    .cons (.roll 2) <|
    .cons .quote <|
    .cons (.roll 2) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.pick 1) <|
      .cons (.pick 1) <|
      .cons (.prim "seq-int.at") <|
      .cons (.lit (.int 1000001)) <|
      .cons (.prim "<") <|
      .cons (.roll 2) <|
      .cons .quote <|
      .cons (.roll 2) <|
      .cons .quote <|
      .cons .compose <|
      .cons (.quotation (
        .cons .swap <|
        .cons .swap <|
        .cons (.lit (.int 1)) <|
        .cons (.prim "+") <|
        .cons (.word "quantities-in-range-from") <|
        .empty)) <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.lit (.bool false)) <|
        .empty)) <|
      .cons .ifThenElse <|
      .empty)) <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.lit (.bool false)) <|
      .empty)) <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.lit (.bool true)) <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `quantities-in-range-from`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "6997392fc891c3e6a1715d95714b888e67b7b98005245b8392a6673e4f9189f9"

/-- The erased word type the image records for `quantities-in-range-from`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many--ρ,v0:Bool^many)"

end «quantities-in-range-from»

namespace «in-range»

/-- The erased kernel program of `in-range`. -/
def body : Program :=
  .cons (.lit (.int (-1))) <|
  .cons (.pick 2) <|
  .cons (.prim "<") <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons .swap <|
    .cons (.lit (.int 1000001)) <|
    .cons (.prim "<") <|
    .cons .swap <|
    .cons .quote <|
    .cons (.quotation (
      .cons .dup <|
      .cons (.prim "seq-int.len") <|
      .cons (.lit (.int 65)) <|
      .cons (.prim "<") <|
      .cons .swap <|
      .cons .quote <|
      .cons (.quotation (
        .cons (.lit (.int 0)) <|
        .cons (.word "quantities-in-range-from") <|
        .empty)) <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.lit (.bool false)) <|
        .empty)) <|
      .cons .ifThenElse <|
      .empty)) <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.lit (.bool false)) <|
      .empty)) <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.lit (.bool false)) <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `in-range`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "abda68038b27cfb8f954600ebf0ff9fc297f2126d2fe975dc2fed885f4b70136"

/-- The erased word type the image records for `in-range`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:SeqInt^many--ρ,v0:Bool^many)"

end «in-range»

namespace «over-si»

/-- The erased kernel program of `over-si`. -/
def body : Program :=
  .cons (.quotation (
    .cons .dup <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .empty

/-- The image's `body_digest` for `over-si`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "9f92d86a26bd41663bf5bcfc8525411fc26210bcf9800860ab913c0799a8074b"

/-- The erased word type the image records for `over-si`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many--ρ,v0:SeqInt^many,v1:Int^many,v2:SeqInt^many)"

end «over-si»

namespace «over-ii»

/-- The erased kernel program of `over-ii`. -/
def body : Program :=
  .cons (.quotation (
    .cons .dup <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .empty

/-- The image's `body_digest` for `over-ii`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "9f92d86a26bd41663bf5bcfc8525411fc26210bcf9800860ab913c0799a8074b"

/-- The erased word type the image records for `over-ii`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many,v1:Int^many,v2:Int^many)"

end «over-ii»

namespace «third-ids»

/-- The erased kernel program of `third-ids`. -/
def body : Program :=
  .cons (.quotation (
    .cons (.word "over-si") <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .empty

/-- The image's `body_digest` for `third-ids`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "2e0b85dca3f7c2447526652f124b70c7046f21d1e508bc748e2e763feb7d2c62"

/-- The erased word type the image records for `third-ids`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many,v2:Int^many--ρ,v0:SeqInt^many,v1:Int^many,v2:Int^many,v3:SeqInt^many)"

end «third-ids»

namespace «distance»

/-- The erased kernel program of `distance`. -/
def body : Program :=
  .cons (.prim "-") <|
  .cons .dup <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "<") <|
  .cons (.quotation (
    .cons (.lit (.int 0)) <|
    .cons .swap <|
    .cons (.prim "-") <|
    .empty)) <|
  .cons (.quotation (.empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `distance`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "42c36e6498c49113fe7f46adc190a9cfad3fd06f4d42951e73c0734a9e77e7ec"

/-- The erased word type the image records for `distance`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many)"

end «distance»

namespace «pair-distance»

/-- The erased kernel program of `pair-distance`. -/
def body : Program :=
  .cons (.word "third-ids") <|
  .cons (.quotation (
    .cons (.word "over-ii") <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons (.prim "seq-int.at") <|
  .cons (.quotation (
    .cons (.word "third-ids") <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons (.quotation (
    .cons (.word "over-ii") <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons (.prim "seq-int.at") <|
  .cons (.word "distance") <|
  .empty

/-- The image's `body_digest` for `pair-distance`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "207b3d3a32fa73efab3f2c28f69043a4a6a84aa45f0351a1144d872dbe29f2de"

/-- The erased word type the image records for `pair-distance`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many,v2:Int^many--ρ,v0:SeqInt^many,v1:Int^many,v2:Int^many,v3:Int^many)"

end «pair-distance»

namespace «bump»

/-- The erased kernel program of `bump`. -/
def body : Program :=
  .cons (.quotation (
    .cons (.lit (.int 1)) <|
    .cons (.prim "+") <|
    .empty)) <|
  .cons .dip <|
  .cons (.lit (.int 1)) <|
  .cons (.prim "+") <|
  .empty

/-- The image's `body_digest` for `bump`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "59c962e7e3c8f3033f3b2b0c13e09d3adc5f7c06b4caa8c4c3194be56eb8b633"

/-- The erased word type the image records for `bump`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many,v1:Int^many)"

end «bump»

namespace «same-id»

/-- The erased kernel program of `same-id`. -/
def body : Program :=
  .cons (.word "pair-distance") <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "=") <|
  .cons (.quotation (
    .cons (.word "bump") <|
    .cons (.word "pair-distance") <|
    .cons (.quotation (
      .cons (.word "bump") <|
      .cons (.word "pair-distance") <|
      .empty)) <|
    .cons .dip <|
    .cons (.prim "+") <|
    .cons (.quotation (
      .cons (.word "bump") <|
      .cons (.word "pair-distance") <|
      .empty)) <|
    .cons .dip <|
    .cons (.prim "+") <|
    .cons (.quotation (
      .cons (.quotation (
        .cons (.lit (.int 3)) <|
        .cons (.prim "-") <|
        .empty)) <|
      .cons .dip <|
      .cons (.lit (.int 3)) <|
      .cons (.prim "-") <|
      .empty)) <|
    .cons .dip <|
    .cons (.lit (.int 0)) <|
    .cons (.prim "=") <|
    .empty)) <|
  .cons (.quotation (
    .cons (.lit (.bool false)) <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `same-id`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "bd9ae331a0555c2e37b46064bfcf083bf2e667f429e1fd06e726e16f0b4b3cbf"

/-- The erased word type the image records for `same-id`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many,v2:Int^many--ρ,v0:SeqInt^many,v1:Int^many,v2:Int^many,v3:Bool^many)"

end «same-id»

namespace «repeat-from»

/-- The erased kernel program of `repeat-from`. -/
def body : Program :=
  .cons (.word "third-ids") <|
  .cons (.prim "seq-int.len") <|
  .cons (.word "over-ii") <|
  .cons .swap <|
  .cons (.prim "<") <|
  .cons (.quotation (
    .cons (.word "same-id") <|
    .cons (.quotation (
      .cons .drop <|
      .cons .drop <|
      .cons .drop <|
      .cons (.lit (.bool true)) <|
      .empty)) <|
    .cons (.quotation (
      .cons (.lit (.int 4)) <|
      .cons (.prim "+") <|
      .cons (.word "repeat-from") <|
      .empty)) <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons (.quotation (
    .cons .drop <|
    .cons (.word "over-si") <|
    .cons (.prim "seq-int.len") <|
    .cons (.quotation (
      .cons .dup <|
      .cons (.lit (.int 8)) <|
      .cons (.prim "+") <|
      .empty)) <|
    .cons .dip <|
    .cons (.prim "<") <|
    .cons (.quotation (
      .cons (.lit (.int 4)) <|
      .cons (.prim "+") <|
      .cons .dup <|
      .cons (.lit (.int 4)) <|
      .cons (.prim "+") <|
      .cons (.word "repeat-from") <|
      .empty)) <|
    .cons (.quotation (
      .cons .drop <|
      .cons .drop <|
      .cons (.lit (.bool false)) <|
      .empty)) <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `repeat-from`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "4863eaf4a3ab2a16cf4c1a3ef26c57c36df117508167c6c2dac633318c87dfd6"

/-- The erased word type the image records for `repeat-from`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many,v2:Int^many--ρ,v0:Bool^many)"

end «repeat-from»

namespace «has-repeat»

/-- The erased kernel program of `has-repeat`. -/
def body : Program :=
  .cons (.lit (.int 0)) <|
  .cons (.lit (.int 4)) <|
  .cons (.word "repeat-from") <|
  .empty

/-- The image's `body_digest` for `has-repeat`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "ef7b0fab3ac8bb31861ad1158a4c015f6eb4de93e10cf12da5ed1d6803f0d1e9"

/-- The erased word type the image records for `has-repeat`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many--ρ,v0:Bool^many)"

end «has-repeat»

namespace «allocate-one»

/-- The erased kernel program of `allocate-one`. -/
def body : Program :=
  .cons (.pick 2) <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "=") <|
  .cons (.quotation (
    .cons (.lit (.int 0)) <|
    .cons (.lit (.int 0)) <|
    .cons (.lit (.int 2)) <|
    .empty)) <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons (.roll 4) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.pick 2) <|
    .cons (.pick 2) <|
    .cons (.lit (.int 1)) <|
    .cons (.prim "+") <|
    .cons (.prim "<") <|
    .cons (.pick 2) <|
    .cons .quote <|
    .cons (.roll 4) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons .swap <|
      .cons (.pick 1) <|
      .cons (.prim "-") <|
      .cons .swap <|
      .cons (.lit (.int 0)) <|
      .empty)) <|
    .cons .compose <|
    .cons (.roll 2) <|
    .cons .quote <|
    .cons (.roll 3) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons .swap <|
      .cons (.pick 1) <|
      .cons .quote <|
      .cons (.quotation (
        .cons (.lit (.int 0)) <|
        .cons (.lit (.int 3)) <|
        .empty)) <|
      .cons .compose <|
      .cons (.roll 2) <|
      .cons .quote <|
      .cons (.quotation (
        .cons (.lit (.int 0)) <|
        .cons .swap <|
        .cons (.lit (.int 1)) <|
        .empty)) <|
      .cons .compose <|
      .cons .ifThenElse <|
      .empty)) <|
    .cons .compose <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `allocate-one`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "58dc5c42e10b308edf20ecf16549f1b0db3b54aa54c886424efe122abb06e0b2"

/-- The erased word type the image records for `allocate-one`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Bool^many--ρ,v0:Int^many,v1:Int^many,v2:Int^many)"

end «allocate-one»

namespace «allocate-from»

/-- The erased kernel program of `allocate-from`. -/
def body : Program :=
  .cons (.pick 2) <|
  .cons (.pick 6) <|
  .cons (.prim "seq-int.len") <|
  .cons (.prim "<") <|
  .cons (.pick 4) <|
  .cons .quote <|
  .cons (.roll 7) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 4) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 5) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.pick 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.pick 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.roll 5) <|
    .cons (.pick 5) <|
    .cons (.pick 5) <|
    .cons (.prim "seq-int.at") <|
    .cons (.pick 4) <|
    .cons (.word "allocate-one") <|
    .cons (.pick 7) <|
    .cons (.pick 6) <|
    .cons (.roll 4) <|
    .cons (.pick 8) <|
    .cons (.lit (.int 1)) <|
    .cons (.prim "+") <|
    .cons (.pick 7) <|
    .cons (.roll 6) <|
    .cons (.prim "seq-int.push") <|
    .cons (.pick 6) <|
    .cons (.roll 6) <|
    .cons (.prim "seq-int.push") <|
    .cons (.word "allocate-from") <|
    .cons (.roll 3) <|
    .cons .drop <|
    .cons (.roll 3) <|
    .cons .drop <|
    .cons (.roll 3) <|
    .cons .drop <|
    .cons (.roll 3) <|
    .cons .drop <|
    .cons (.roll 3) <|
    .cons .drop <|
    .empty)) <|
  .cons .compose <|
  .cons (.roll 4) <|
  .cons .quote <|
  .cons (.roll 4) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.roll 2) <|
    .cons (.roll 2) <|
    .cons (.roll 2) <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `allocate-from`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "8b791d929fa24456d4c5ce0a1e004f585b59fccf3827b09e3d5943b977292bd9"

/-- The erased word type the image records for `allocate-from`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Bool^many,v2:Int^many,v3:Int^many,v4:SeqInt^many,v5:SeqInt^many--ρ,v0:Int^many,v1:SeqInt^many,v2:SeqInt^many)"

end «allocate-from»

namespace «allocate-batch»

/-- The erased kernel program of `allocate-batch`. -/
def body : Program :=
  .cons (.pick 3) <|
  .cons (.pick 1) <|
  .cons (.word "in-range") <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.roll 3) <|
    .cons (.word "has-repeat") <|
    .cons (.quotation (
      .cons (.lit (.int 2)) <|
      .cons (.lit (.int 0)) <|
      .cons (.prim "seq-int.empty") <|
      .cons (.prim "seq-int.empty") <|
      .empty)) <|
    .cons (.roll 4) <|
    .cons .quote <|
    .cons (.roll 4) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.roll 3) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.lit (.int 0)) <|
      .cons (.roll 3) <|
      .cons (.roll 3) <|
      .cons (.roll 3) <|
      .cons (.lit (.int 0)) <|
      .cons (.prim "seq-int.empty") <|
      .cons (.prim "seq-int.empty") <|
      .cons (.word "allocate-from") <|
      .empty)) <|
    .cons .compose <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.lit (.int 1)) <|
    .cons (.lit (.int 0)) <|
    .cons (.prim "seq-int.empty") <|
    .cons (.prim "seq-int.empty") <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `allocate-batch`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "527a8583a4f31cb62d5a4eda4e749464dbf09ff2dcd1f3bf3876458aabbf9eba"

/-- The erased word type the image records for `allocate-batch`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Bool^many,v2:SeqInt^many,v3:SeqInt^many--ρ,v0:Int^many,v1:Int^many,v2:SeqInt^many,v3:SeqInt^many)"

end «allocate-batch»

/-- Every word, in declaration order: its name, body and body digest. -/
def words : List (String × Program × String) := [
  ("quantities-in-range-from", «quantities-in-range-from».body, «quantities-in-range-from».bodyDigest),
  ("in-range", «in-range».body, «in-range».bodyDigest),
  ("over-si", «over-si».body, «over-si».bodyDigest),
  ("over-ii", «over-ii».body, «over-ii».bodyDigest),
  ("third-ids", «third-ids».body, «third-ids».bodyDigest),
  ("distance", «distance».body, «distance».bodyDigest),
  ("pair-distance", «pair-distance».body, «pair-distance».bodyDigest),
  ("bump", «bump».body, «bump».bodyDigest),
  ("same-id", «same-id».body, «same-id».bodyDigest),
  ("repeat-from", «repeat-from».body, «repeat-from».bodyDigest),
  ("has-repeat", «has-repeat».body, «has-repeat».bodyDigest),
  ("allocate-one", «allocate-one».body, «allocate-one».bodyDigest),
  ("allocate-from", «allocate-from».body, «allocate-from».bodyDigest),
  ("allocate-batch", «allocate-batch».body, «allocate-batch».bodyDigest)]

/-- The dictionary the reference runner builds for this source. -/
def dictionary : Dictionary
  | "quantities-in-range-from" => some { type := adapterWordType, body := «quantities-in-range-from».body }
  | "in-range" => some { type := adapterWordType, body := «in-range».body }
  | "over-si" => some { type := adapterWordType, body := «over-si».body }
  | "over-ii" => some { type := adapterWordType, body := «over-ii».body }
  | "third-ids" => some { type := adapterWordType, body := «third-ids».body }
  | "distance" => some { type := adapterWordType, body := «distance».body }
  | "pair-distance" => some { type := adapterWordType, body := «pair-distance».body }
  | "bump" => some { type := adapterWordType, body := «bump».body }
  | "same-id" => some { type := adapterWordType, body := «same-id».body }
  | "repeat-from" => some { type := adapterWordType, body := «repeat-from».body }
  | "has-repeat" => some { type := adapterWordType, body := «has-repeat».body }
  | "allocate-one" => some { type := adapterWordType, body := «allocate-one».body }
  | "allocate-from" => some { type := adapterWordType, body := «allocate-from».body }
  | "allocate-batch" => some { type := adapterWordType, body := «allocate-batch».body }
  | _ => none

/-! Each word's dictionary entry, which a proof unfolding a call to it needs. -/

theorem «quantities-in-range-from».entry :
    dictionary "quantities-in-range-from" = some { type := adapterWordType, body := «quantities-in-range-from».body } := rfl

theorem «in-range».entry :
    dictionary "in-range" = some { type := adapterWordType, body := «in-range».body } := rfl

theorem «over-si».entry :
    dictionary "over-si" = some { type := adapterWordType, body := «over-si».body } := rfl

theorem «over-ii».entry :
    dictionary "over-ii" = some { type := adapterWordType, body := «over-ii».body } := rfl

theorem «third-ids».entry :
    dictionary "third-ids" = some { type := adapterWordType, body := «third-ids».body } := rfl

theorem «distance».entry :
    dictionary "distance" = some { type := adapterWordType, body := «distance».body } := rfl

theorem «pair-distance».entry :
    dictionary "pair-distance" = some { type := adapterWordType, body := «pair-distance».body } := rfl

theorem «bump».entry :
    dictionary "bump" = some { type := adapterWordType, body := «bump».body } := rfl

theorem «same-id».entry :
    dictionary "same-id" = some { type := adapterWordType, body := «same-id».body } := rfl

theorem «repeat-from».entry :
    dictionary "repeat-from" = some { type := adapterWordType, body := «repeat-from».body } := rfl

theorem «has-repeat».entry :
    dictionary "has-repeat" = some { type := adapterWordType, body := «has-repeat».body } := rfl

theorem «allocate-one».entry :
    dictionary "allocate-one" = some { type := adapterWordType, body := «allocate-one».body } := rfl

theorem «allocate-from».entry :
    dictionary "allocate-from" = some { type := adapterWordType, body := «allocate-from».body } := rfl

theorem «allocate-batch».entry :
    dictionary "allocate-batch" = some { type := adapterWordType, body := «allocate-batch».body } := rfl

end Firth.Exports.Inventory.Allocator
