import FirthReferenceRun

/-!
Generated by `lake exe firthExportLean` from `examples/inventory/allocator.firth`. Do not edit:
`python3 tools/loop/update_kernel_exports.py` regenerates it, and CI fails when
this file differs from what the elaborator produces from that source.

Each word's `body` is the erased kernel program the elaborator checked and the
compiler accepted, and `bodyDigest` is the `body_digest` of that program in the
VM image. `FirthExportsTest` lowers every `body` again and fails unless it
hashes to `bodyDigest`.

`dictionary`, `Firth.ReferenceRun.adapterGamma` and `defaultCosts` are exactly
what the reference runner executes these words with.
-/

namespace Firth.Exports.Inventory.Allocator
open Firth.Interpreter
open Firth.ReferenceRun

/-- SHA-256 of the source text these definitions were generated from. -/
def sourceDigest : String := "33adee2a28d0775a77f4bc03070b15fcce3ff65b14403a8a44890e023b55d2b0"

namespace «quantities-in-range-from»

/-- The erased kernel program of `quantities-in-range-from`. -/
def body : Program :=
  .cons .dup <|
  .cons (.pick 2) <|
  .cons (.prim "seq-int.len") <|
  .cons (.prim "<") <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.lit (.int 0)) <|
    .cons (.pick 2) <|
    .cons (.pick 2) <|
    .cons (.prim "seq-int.at") <|
    .cons (.prim "<") <|
    .cons (.roll 2) <|
    .cons .quote <|
    .cons (.roll 2) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.pick 1) <|
      .cons (.pick 1) <|
      .cons (.prim "seq-int.at") <|
      .cons (.lit (.int 1000001)) <|
      .cons (.prim "<") <|
      .cons (.roll 2) <|
      .cons .quote <|
      .cons (.roll 2) <|
      .cons .quote <|
      .cons .compose <|
      .cons (.quotation (
        .cons .swap <|
        .cons .swap <|
        .cons (.lit (.int 1)) <|
        .cons (.prim "+") <|
        .cons (.word "quantities-in-range-from") <|
        .empty)) <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.lit (.bool false)) <|
        .empty)) <|
      .cons .ifThenElse <|
      .empty)) <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.lit (.bool false)) <|
      .empty)) <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.lit (.bool true)) <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `quantities-in-range-from`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "6997392fc891c3e6a1715d95714b888e67b7b98005245b8392a6673e4f9189f9"

/-- The erased word type the image records for `quantities-in-range-from`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many--ρ,v0:Bool^many)"

end «quantities-in-range-from»

namespace «in-range»

/-- The erased kernel program of `in-range`. -/
def body : Program :=
  .cons (.lit (.int (-1))) <|
  .cons (.pick 2) <|
  .cons (.prim "<") <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons .swap <|
    .cons (.lit (.int 1000001)) <|
    .cons (.prim "<") <|
    .cons .swap <|
    .cons .quote <|
    .cons (.quotation (
      .cons .dup <|
      .cons (.prim "seq-int.len") <|
      .cons (.lit (.int 65)) <|
      .cons (.prim "<") <|
      .cons .swap <|
      .cons .quote <|
      .cons (.quotation (
        .cons (.lit (.int 0)) <|
        .cons (.word "quantities-in-range-from") <|
        .empty)) <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.lit (.bool false)) <|
        .empty)) <|
      .cons .ifThenElse <|
      .empty)) <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.lit (.bool false)) <|
      .empty)) <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.lit (.bool false)) <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `in-range`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "abda68038b27cfb8f954600ebf0ff9fc297f2126d2fe975dc2fed885f4b70136"

/-- The erased word type the image records for `in-range`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:SeqInt^many--ρ,v0:Bool^many)"

end «in-range»

namespace «distance»

/-- The erased kernel program of `distance`. -/
def body : Program :=
  .cons (.prim "-") <|
  .cons .dup <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "<") <|
  .cons (.quotation (
    .cons (.lit (.int 0)) <|
    .cons .swap <|
    .cons (.prim "-") <|
    .empty)) <|
  .cons (.quotation (.empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `distance`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "42c36e6498c49113fe7f46adc190a9cfad3fd06f4d42951e73c0734a9e77e7ec"

/-- The erased word type the image records for `distance`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many)"

end «distance»

namespace «part-distance»

/-- The erased kernel program of `part-distance`. -/
def body : Program :=
  .cons (.pick 3) <|
  .cons (.roll 3) <|
  .cons (.pick 2) <|
  .cons (.prim "+") <|
  .cons (.prim "seq-int.at") <|
  .cons (.roll 3) <|
  .cons (.roll 3) <|
  .cons (.roll 3) <|
  .cons (.prim "+") <|
  .cons (.prim "seq-int.at") <|
  .cons (.word "distance") <|
  .empty

/-- The image's `body_digest` for `part-distance`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "0c201fd6539dd10a587a712343a319724fdc75c5d0605bf908e57913fcb50923"

/-- The erased word type the image records for `part-distance`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many,v2:Int^many,v3:Int^many--ρ,v0:Int^many)"

end «part-distance»

namespace «same-id»

/-- The erased kernel program of `same-id`. -/
def body : Program :=
  .cons (.pick 2) <|
  .cons (.pick 2) <|
  .cons (.pick 2) <|
  .cons (.lit (.int 0)) <|
  .cons (.word "part-distance") <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "=") <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.pick 2) <|
    .cons (.pick 2) <|
    .cons (.pick 2) <|
    .cons (.lit (.int 1)) <|
    .cons (.word "part-distance") <|
    .cons (.pick 3) <|
    .cons (.pick 3) <|
    .cons (.pick 3) <|
    .cons (.lit (.int 2)) <|
    .cons (.word "part-distance") <|
    .cons (.prim "+") <|
    .cons (.roll 3) <|
    .cons (.roll 3) <|
    .cons (.roll 3) <|
    .cons (.lit (.int 3)) <|
    .cons (.word "part-distance") <|
    .cons (.prim "+") <|
    .cons (.lit (.int 0)) <|
    .cons (.prim "=") <|
    .empty)) <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.lit (.bool false)) <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `same-id`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "f435b7b52fa5beccc0a6610977a7d1d075234aeccfd1844d780551871bec02d1"

/-- The erased word type the image records for `same-id`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many,v2:Int^many--ρ,v0:Bool^many)"

end «same-id»

namespace «repeat-from»

/-- The erased kernel program of `repeat-from`. -/
def body : Program :=
  .cons .dup <|
  .cons (.pick 3) <|
  .cons (.prim "seq-int.len") <|
  .cons (.prim "<") <|
  .cons (.pick 3) <|
  .cons .quote <|
  .cons (.pick 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.pick 2) <|
    .cons (.pick 2) <|
    .cons (.pick 2) <|
    .cons (.word "same-id") <|
    .cons (.quotation (
      .cons (.lit (.bool true)) <|
      .empty)) <|
    .cons (.roll 4) <|
    .cons .quote <|
    .cons (.roll 4) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.roll 3) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.roll 2) <|
      .cons (.roll 2) <|
      .cons (.roll 2) <|
      .cons (.lit (.int 4)) <|
      .cons (.prim "+") <|
      .cons (.word "repeat-from") <|
      .empty)) <|
    .cons .compose <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.pick 1) <|
    .cons (.lit (.int 8)) <|
    .cons (.prim "+") <|
    .cons (.pick 1) <|
    .cons (.prim "seq-int.len") <|
    .cons (.prim "<") <|
    .cons .swap <|
    .cons .quote <|
    .cons (.roll 2) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons .swap <|
      .cons (.pick 1) <|
      .cons (.lit (.int 4)) <|
      .cons (.prim "+") <|
      .cons (.roll 2) <|
      .cons (.lit (.int 8)) <|
      .cons (.prim "+") <|
      .cons (.word "repeat-from") <|
      .empty)) <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.lit (.bool false)) <|
      .empty)) <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `repeat-from`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "688e568967d9a69241259facb32d5fa6b38376ff7dbf75c4fd07936480c2f819"

/-- The erased word type the image records for `repeat-from`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many,v2:Int^many--ρ,v0:Bool^many)"

end «repeat-from»

namespace «has-repeat»

/-- The erased kernel program of `has-repeat`. -/
def body : Program :=
  .cons (.lit (.int 0)) <|
  .cons (.lit (.int 4)) <|
  .cons (.word "repeat-from") <|
  .empty

/-- The image's `body_digest` for `has-repeat`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "ef7b0fab3ac8bb31861ad1158a4c015f6eb4de93e10cf12da5ed1d6803f0d1e9"

/-- The erased word type the image records for `has-repeat`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many--ρ,v0:Bool^many)"

end «has-repeat»

namespace «allocate-one»

/-- The erased kernel program of `allocate-one`. -/
def body : Program :=
  .cons (.pick 2) <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "=") <|
  .cons (.quotation (
    .cons (.lit (.int 0)) <|
    .cons (.lit (.int 0)) <|
    .cons (.lit (.int 2)) <|
    .empty)) <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons (.roll 4) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.pick 2) <|
    .cons (.pick 2) <|
    .cons (.lit (.int 1)) <|
    .cons (.prim "+") <|
    .cons (.prim "<") <|
    .cons (.pick 2) <|
    .cons .quote <|
    .cons (.roll 4) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons .swap <|
      .cons (.pick 1) <|
      .cons (.prim "-") <|
      .cons .swap <|
      .cons (.lit (.int 0)) <|
      .empty)) <|
    .cons .compose <|
    .cons (.roll 2) <|
    .cons .quote <|
    .cons (.roll 3) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons .swap <|
      .cons (.pick 1) <|
      .cons .quote <|
      .cons (.quotation (
        .cons (.lit (.int 0)) <|
        .cons (.lit (.int 3)) <|
        .empty)) <|
      .cons .compose <|
      .cons (.roll 2) <|
      .cons .quote <|
      .cons (.quotation (
        .cons (.lit (.int 0)) <|
        .cons .swap <|
        .cons (.lit (.int 1)) <|
        .empty)) <|
      .cons .compose <|
      .cons .ifThenElse <|
      .empty)) <|
    .cons .compose <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `allocate-one`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "58dc5c42e10b308edf20ecf16549f1b0db3b54aa54c886424efe122abb06e0b2"

/-- The erased word type the image records for `allocate-one`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Bool^many--ρ,v0:Int^many,v1:Int^many,v2:Int^many)"

end «allocate-one»

namespace «allocate-from»

/-- The erased kernel program of `allocate-from`. -/
def body : Program :=
  .cons (.pick 2) <|
  .cons (.pick 6) <|
  .cons (.prim "seq-int.len") <|
  .cons (.prim "<") <|
  .cons (.pick 4) <|
  .cons .quote <|
  .cons (.roll 7) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 4) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 5) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.pick 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.pick 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.roll 5) <|
    .cons (.pick 5) <|
    .cons (.pick 5) <|
    .cons (.prim "seq-int.at") <|
    .cons (.pick 4) <|
    .cons (.word "allocate-one") <|
    .cons (.pick 7) <|
    .cons (.pick 6) <|
    .cons (.roll 4) <|
    .cons (.pick 8) <|
    .cons (.lit (.int 1)) <|
    .cons (.prim "+") <|
    .cons (.pick 7) <|
    .cons (.roll 6) <|
    .cons (.prim "seq-int.push") <|
    .cons (.pick 6) <|
    .cons (.roll 6) <|
    .cons (.prim "seq-int.push") <|
    .cons (.word "allocate-from") <|
    .cons (.roll 3) <|
    .cons .drop <|
    .cons (.roll 3) <|
    .cons .drop <|
    .cons (.roll 3) <|
    .cons .drop <|
    .cons (.roll 3) <|
    .cons .drop <|
    .cons (.roll 3) <|
    .cons .drop <|
    .empty)) <|
  .cons .compose <|
  .cons (.roll 4) <|
  .cons .quote <|
  .cons (.roll 4) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.roll 2) <|
    .cons (.roll 2) <|
    .cons (.roll 2) <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `allocate-from`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "8b791d929fa24456d4c5ce0a1e004f585b59fccf3827b09e3d5943b977292bd9"

/-- The erased word type the image records for `allocate-from`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Bool^many,v2:Int^many,v3:Int^many,v4:SeqInt^many,v5:SeqInt^many--ρ,v0:Int^many,v1:SeqInt^many,v2:SeqInt^many)"

end «allocate-from»

namespace «allocate-batch»

/-- The erased kernel program of `allocate-batch`. -/
def body : Program :=
  .cons (.pick 3) <|
  .cons (.pick 1) <|
  .cons (.word "in-range") <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.roll 3) <|
    .cons (.word "has-repeat") <|
    .cons (.quotation (
      .cons (.lit (.int 2)) <|
      .cons (.lit (.int 0)) <|
      .cons (.prim "seq-int.empty") <|
      .cons (.prim "seq-int.empty") <|
      .empty)) <|
    .cons (.roll 4) <|
    .cons .quote <|
    .cons (.roll 4) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.roll 3) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.lit (.int 0)) <|
      .cons (.roll 3) <|
      .cons (.roll 3) <|
      .cons (.roll 3) <|
      .cons (.lit (.int 0)) <|
      .cons (.prim "seq-int.empty") <|
      .cons (.prim "seq-int.empty") <|
      .cons (.word "allocate-from") <|
      .empty)) <|
    .cons .compose <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.lit (.int 1)) <|
    .cons (.lit (.int 0)) <|
    .cons (.prim "seq-int.empty") <|
    .cons (.prim "seq-int.empty") <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `allocate-batch`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "527a8583a4f31cb62d5a4eda4e749464dbf09ff2dcd1f3bf3876458aabbf9eba"

/-- The erased word type the image records for `allocate-batch`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Bool^many,v2:SeqInt^many,v3:SeqInt^many--ρ,v0:Int^many,v1:Int^many,v2:SeqInt^many,v3:SeqInt^many)"

end «allocate-batch»

/-- Every word, in declaration order: its name, body, body digest and erased
type. -/
def words : List (String × Program × String × String) := [
  ("quantities-in-range-from", «quantities-in-range-from».body, «quantities-in-range-from».bodyDigest, «quantities-in-range-from».erasedType),
  ("in-range", «in-range».body, «in-range».bodyDigest, «in-range».erasedType),
  ("distance", «distance».body, «distance».bodyDigest, «distance».erasedType),
  ("part-distance", «part-distance».body, «part-distance».bodyDigest, «part-distance».erasedType),
  ("same-id", «same-id».body, «same-id».bodyDigest, «same-id».erasedType),
  ("repeat-from", «repeat-from».body, «repeat-from».bodyDigest, «repeat-from».erasedType),
  ("has-repeat", «has-repeat».body, «has-repeat».bodyDigest, «has-repeat».erasedType),
  ("allocate-one", «allocate-one».body, «allocate-one».bodyDigest, «allocate-one».erasedType),
  ("allocate-from", «allocate-from».body, «allocate-from».bodyDigest, «allocate-from».erasedType),
  ("allocate-batch", «allocate-batch».body, «allocate-batch».bodyDigest, «allocate-batch».erasedType)]

/-- The dictionary the reference runner builds for this source. -/
def dictionary : Dictionary
  | "quantities-in-range-from" => some { type := adapterWordType, body := «quantities-in-range-from».body }
  | "in-range" => some { type := adapterWordType, body := «in-range».body }
  | "distance" => some { type := adapterWordType, body := «distance».body }
  | "part-distance" => some { type := adapterWordType, body := «part-distance».body }
  | "same-id" => some { type := adapterWordType, body := «same-id».body }
  | "repeat-from" => some { type := adapterWordType, body := «repeat-from».body }
  | "has-repeat" => some { type := adapterWordType, body := «has-repeat».body }
  | "allocate-one" => some { type := adapterWordType, body := «allocate-one».body }
  | "allocate-from" => some { type := adapterWordType, body := «allocate-from».body }
  | "allocate-batch" => some { type := adapterWordType, body := «allocate-batch».body }
  | _ => none

/-! Each word's dictionary entry, which a proof unfolding a call to it needs. -/

theorem «quantities-in-range-from».entry :
    dictionary "quantities-in-range-from" = some { type := adapterWordType, body := «quantities-in-range-from».body } := rfl

theorem «in-range».entry :
    dictionary "in-range" = some { type := adapterWordType, body := «in-range».body } := rfl

theorem «distance».entry :
    dictionary "distance" = some { type := adapterWordType, body := «distance».body } := rfl

theorem «part-distance».entry :
    dictionary "part-distance" = some { type := adapterWordType, body := «part-distance».body } := rfl

theorem «same-id».entry :
    dictionary "same-id" = some { type := adapterWordType, body := «same-id».body } := rfl

theorem «repeat-from».entry :
    dictionary "repeat-from" = some { type := adapterWordType, body := «repeat-from».body } := rfl

theorem «has-repeat».entry :
    dictionary "has-repeat" = some { type := adapterWordType, body := «has-repeat».body } := rfl

theorem «allocate-one».entry :
    dictionary "allocate-one" = some { type := adapterWordType, body := «allocate-one».body } := rfl

theorem «allocate-from».entry :
    dictionary "allocate-from" = some { type := adapterWordType, body := «allocate-from».body } := rfl

theorem «allocate-batch».entry :
    dictionary "allocate-batch" = some { type := adapterWordType, body := «allocate-batch».body } := rfl

end Firth.Exports.Inventory.Allocator
