#!/usr/bin/env python3
"""Drift test for the SMT translation-rule and soundness-proof hashes.

`Firth.Smt.defaultSmtProofBindings` binds every SMT request and discharge
record to the translation it was produced under. Those hashes are generated by
`tools/loop/update_smt_proof_bindings.py`, so an edit to a translation rule or
one of its soundness proofs without a regeneration would leave a record
claiming provenance it no longer has. This test catches that in under a
second and without a Lean build.
"""

from __future__ import annotations

import subprocess
import sys
import unittest
from pathlib import Path

LOOP = Path(__file__).parent


class SmtProofBindingsTests(unittest.TestCase):
    def test_the_bindings_match_the_marked_regions(self) -> None:
        result = subprocess.run(
            [sys.executable, str(LOOP / "update_smt_proof_bindings.py"), "--check"],
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stderr or result.stdout)

    def test_the_generator_is_idempotent(self) -> None:
        """Running the generator twice must be a fixed point.

        The hashes live outside every marked region precisely so that writing
        them cannot change what they cover; this asserts that property rather
        than trusting the layout.
        """
        source = LOOP.parents[1] / "src" / "smt" / "Firth" / "SmtBoundary.lean"
        before = source.read_bytes()
        try:
            first = subprocess.run(
                [sys.executable, str(LOOP / "update_smt_proof_bindings.py")],
                text=True,
                capture_output=True,
                check=False,
            )
            self.assertEqual(first.returncode, 0, first.stderr)
            self.assertEqual(source.read_bytes(), before, "the generator was not at a fixed point")
        finally:
            source.write_bytes(before)


if __name__ == "__main__":
    unittest.main()
