#!/usr/bin/env python3
"""Regenerate the check that the Lean allocation rule agrees with the frozen corpus.

`src/proofs/Inventory/Spec.lean` states the allocation rule of
specs/inventory-allocation.md as `allocateAll` and proves the spec's required
properties of it. Those proofs are only as good as the rule's agreement with
the frozen contract, so this script writes one `#guard` per successful case in
specs/inventory-allocation-cases.json to
`src/prooftests/InventorySpecCorpus.lean`: `lake build` evaluates each and
fails if `allocateAll` gives a different remaining stock, allocation or reason
for any of them. Error cases are not covered: `allocateAll` is the calculation
after validation.

Usage: python3 tools/loop/update_inventory_spec_corpus.py [--check]

`--check` exits non-zero if the checked-in file differs from what the corpus
gives, so a corpus change cannot leave the check stale.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CASES = ROOT / "specs" / "inventory-allocation-cases.json"
OUTPUT = ROOT / "src" / "prooftests" / "InventorySpecCorpus.lean"
REASONS = {"fulfilled": 0, "partial": 1, "out-of-stock": 2, "insufficient-stock": 3}


def lean_list(values: list[int]) -> str:
    return "[" + ", ".join(str(value) for value in values) + "]"


def render() -> str:
    cases = json.loads(CASES.read_text(encoding="utf-8"))["cases"]
    lines = []
    for case in cases:
        expected = case["expected"]
        if expected["status"] != "ok":
            continue
        given = case["input"]
        whole = "true" if given["policy"] == "all-or-nothing" else "false"
        quantities = [request["quantity"] for request in given["requests"]]
        allocated = [allocation["quantity"] for allocation in expected["allocations"]]
        reasons = [REASONS[allocation["reason"]] for allocation in expected["allocations"]]
        lines.append(f"-- {case['name']}\n#guard allocateAll {whole} {given['available']} "
                     f"{lean_list(quantities)} ==\n  ({expected['remaining']}, "
                     f"{lean_list(allocated)}, {lean_list(reasons)})")
    if not lines:
        raise SystemExit(f"no successful cases in {CASES}")
    return ("-- Generated by tools/loop/update_inventory_spec_corpus.py from\n"
            "-- specs/inventory-allocation-cases.json; do not edit.\n"
            "import proofs.Inventory.Spec\n\n"
            "/-! `allocateAll` reproduces every successful case of the frozen inventory\n"
            f"corpus ({len(lines)} cases): remaining stock, allocations and reasons. -/\n\n"
            "namespace Firth.ProofTests.InventorySpecCorpus\n"
            "open Firth.Proofs.Inventory.Spec\n\n"
            + "\n\n".join(lines)
            + "\n\nend Firth.ProofTests.InventorySpecCorpus\n")


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != text:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"inventory spec corpus check matches the corpus ({text.count('#guard')} cases)")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
