#!/usr/bin/env python3
"""Regenerate the check that the Lean allocation rule agrees with the frozen corpus.

`src/proofs/Inventory/Spec.lean` states the allocation rule of
specs/inventory-allocation.md as `allocateAll` and proves the spec's required
properties of it. Those proofs are only as good as the rule's agreement with
the frozen contract, so this script writes one `#guard` per successful case in
specs/inventory-allocation-cases.json to
`src/proofs/Inventory/SpecCorpus.lean`: `lake build` evaluates each and
fails if `allocateAll` gives a different remaining stock, allocation or reason
for any of them.

It also writes one `#guard` on `Host.hostSpec`, the result
`allocate_batch_host_contract` proves the program returns on the encoded IDs,
for every case the host passes to the component (error cases included): the
input goes through the host's own checks (`examples/inventory/run_cases.py`)
and reaches Lean as ID strings, and the expected code, stock, allocations and
reasons come from the corpus.

Usage: python3 tools/loop/update_inventory_spec_corpus.py [--check]

`--check` exits non-zero if the checked-in file differs from what the corpus
gives, so a corpus change cannot leave the check stale.
`test_update_inventory_spec_corpus.py` plants stale output and an edited corpus
and requires `--check` to reject both.

Language need (AGENTS.md rule 5): the allocator's proofs show the program
computes `allocateAll`, which is only worth something if `allocateAll` is the
contract's rule. This ties the Lean statement to the frozen corpus's expected
results, which were written independently of it (rule 10).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "examples" / "inventory"))
import run_cases as host  # noqa: E402  (the host's checks)

CASES = ROOT / "specs" / "inventory-allocation-cases.json"
OUTPUT = ROOT / "src" / "proofs" / "Inventory" / "SpecCorpus.lean"
REASONS = {"fulfilled": 0, "partial": 1, "out-of-stock": 2, "insufficient-stock": 3}
CODES = {"invalid-range": 1, "duplicate-id": 2}


def lean_int(value: int) -> str:
    return f"({value})" if value < 0 else str(value)


def lean_list(values: list[int]) -> str:
    return "[" + ", ".join(str(value) for value in values) + "]"


def lean_strings(values: list[str]) -> str:
    return "[" + ", ".join(json.dumps(value) for value in values) + "]"


def component_guard(case: dict) -> str | None:
    """`hostSpec` on what the host hands the component, against the corpus's
    expected result, or None when the host rejects the input itself."""
    checked = host.host_check(case["input"])
    if isinstance(checked, dict):
        return None
    available, whole, ids, quantities = checked
    expected = case["expected"]
    if expected["status"] == "ok":
        result = (f"(0, {lean_int(expected['remaining'])}, "
                  f"{lean_list([a['quantity'] for a in expected['allocations']])}, "
                  f"{lean_list([REASONS[a['reason']] for a in expected['allocations']])})")
    else:
        result = f"({CODES[expected['code']]}, 0, [], [])"
    return (f"-- {case['name']}\n#guard hostSpec {lean_int(available)} "
            f"{'true' if whole else 'false'}\n    {lean_strings(ids)}\n    {lean_list(quantities)} ==\n"
            f"  {result}")


def render() -> str:
    cases = json.loads(CASES.read_text(encoding="utf-8"))["cases"]
    lines = []
    for case in cases:
        expected = case["expected"]
        if expected["status"] != "ok":
            continue
        given = case["input"]
        whole = "true" if given["policy"] == "all-or-nothing" else "false"
        quantities = [request["quantity"] for request in given["requests"]]
        allocated = [allocation["quantity"] for allocation in expected["allocations"]]
        reasons = [REASONS[allocation["reason"]] for allocation in expected["allocations"]]
        lines.append(f"-- {case['name']}\n#guard allocateAll {whole} {given['available']} "
                     f"{lean_list(quantities)} ==\n  ({expected['remaining']}, "
                     f"{lean_list(allocated)}, {lean_list(reasons)})")
    if not lines:
        raise SystemExit(f"no successful cases in {CASES}")
    component = [guard for guard in map(component_guard, cases) if guard is not None]
    errors = sum(1 for case in cases if case["expected"]["status"] != "ok"
                 and not isinstance(host.host_check(case["input"]), dict))
    return ("-- Generated by tools/loop/update_inventory_spec_corpus.py from\n"
            "-- specs/inventory-allocation-cases.json; do not edit.\n"
            "import proofs.Inventory.Host\n\n"
            "/-! `allocateAll` reproduces every successful case of the frozen inventory\n"
            f"corpus ({len(lines)} cases): remaining stock, allocations and reasons. -/\n\n"
            "namespace Firth.Proofs.Inventory.SpecCorpus\n"
            "open Firth.Proofs.Inventory.Spec\n\n"
            + "\n\n".join(lines)
            + "\n\n/-! `hostSpec`, what `allocate_batch_host_contract` proves `allocate-batch`\n"
            f"returns, gives the expected result on every case the host hands the component\n"
            f"({len(component)} cases, {errors} of them errors), on the ID strings. -/\n\n"
            "open Firth.Proofs.Inventory.Host\n\n"
            + "\n\n".join(component)
            + "\n\nend Firth.Proofs.Inventory.SpecCorpus\n")


def main() -> int:
    text = render()
    if "--check" in sys.argv[1:]:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != text:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run {Path(__file__).name}", file=sys.stderr)
            return 1
        print(f"inventory spec corpus check matches the corpus ({text.count('#guard')} cases)")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
