#!/usr/bin/env python3
"""Regenerate the Lean exports of Firth sources' erased kernel programs.

Every source listed in `src/exports/manifest.json` is exported by
`lake exe firthExportLean` to `src/exports/<Module path>.lean`, a Lean module
defining each word's kernel program next to its image `body_digest` (see
`src/compiler/Firth/ExportLean.lean`). `src/exports/All.lean` imports them all
and lists them for `FirthExportsTest`, which lowers every exported body again
and fails unless it hashes to the recorded digest.

Usage: python3 tools/loop/update_kernel_exports.py [--check]

Run from the repository root after `lake build`. `--check` regenerates in
memory and exits non-zero if any checked-in file differs, is missing, or is an
export no manifest entry produces. It also re-exports a copy of one source
with a planted edit and fails unless that word's exported body changes, so
the check is shown to see a source change.
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
EXPORTS = ROOT / "src" / "exports"
MANIFEST = EXPORTS / "manifest.json"
EXPORTER = ROOT / ".lake" / "build" / "bin" / "firthExportLean"
# The planted edit: `abs` compares with 1 instead of 0.
PLANT_SOURCE = "examples/programs/signed.firth"
PLANT_MODULE = "Programs.Signed"
PLANT_WORD = "abs"
PLANT_EDIT = ("{ n 0 prim < ", "{ n 1 prim < ")
MODULE = re.compile(r"^[A-Z][A-Za-z0-9_]*(\.[A-Z][A-Za-z0-9_]*)*$")


def load_manifest() -> list[tuple[str, str]]:
    entries = json.loads(MANIFEST.read_text(encoding="utf-8"))
    pairs: list[tuple[str, str]] = []
    for entry in entries:
        if set(entry) != {"source", "module"}:
            raise SystemExit(f"{MANIFEST}: each entry has exactly source and module")
        source, module = entry["source"], entry["module"]
        if not MODULE.match(module) or module == "All":
            raise SystemExit(f"{MANIFEST}: invalid module name {module!r}")
        if not (ROOT / source).is_file():
            raise SystemExit(f"{MANIFEST}: missing source {source}")
        pairs.append((source, module))
    modules = [module for _, module in pairs]
    if len(set(modules)) != len(modules):
        raise SystemExit(f"{MANIFEST}: duplicate module name")
    return pairs


def module_path(module: str) -> Path:
    return EXPORTS.joinpath(*module.split(".")).with_suffix(".lean")


def export(source: str, module: str) -> str:
    result = subprocess.run([str(EXPORTER), source, module], cwd=ROOT,
                            capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise SystemExit(f"firthExportLean failed for {source}:\n{result.stderr}")
    return result.stdout


def word_block(text: str, word: str) -> str:
    """The exported definitions of one word: its namespace up to its digest."""
    match = re.search(rf"namespace «{re.escape(word)}»\n(.*?)\ndef bodyDigest[^\n]*\n",
                      text, re.S)
    if match is None:
        raise SystemExit(f"no exported word {word}")
    return match.group(0)


def planted_edit_detected() -> bool:
    """Export a copy of PLANT_SOURCE with PLANT_EDIT applied, and report
    whether PLANT_WORD's body and digest differ from the unedited export."""
    original = (ROOT / PLANT_SOURCE).read_text(encoding="utf-8")
    old, new = PLANT_EDIT
    if original.count(old) != 1:
        raise SystemExit(f"planted edit {old!r} does not occur once in {PLANT_SOURCE}")
    with tempfile.TemporaryDirectory() as scratch:
        planted = Path(scratch) / Path(PLANT_SOURCE).name
        planted.write_text(original.replace(old, new), encoding="utf-8")
        edited = export(str(planted), PLANT_MODULE)
    unedited = export(PLANT_SOURCE, PLANT_MODULE)
    return word_block(edited, PLANT_WORD) != word_block(unedited, PLANT_WORD)


def aggregate(pairs: list[tuple[str, str]]) -> str:
    imports = "\n".join(f"import exports.{module}" for _, module in pairs)
    rows = ",\n".join(
        f'  ({json.dumps(module)}, {json.dumps(source)}, Firth.Exports.{module}.words)'
        for source, module in pairs)
    return f"""{imports}

/-!
Generated by `python3 tools/loop/update_kernel_exports.py` from
`src/exports/manifest.json`. Do not edit.
-/

namespace Firth.Exports

/-- Every exported source: its module, its source path, and its words (name,
kernel program, body digest, erased type) in declaration order. -/
def all : List (String × String × List (String × Firth.Interpreter.Program × String × String)) := [
{rows}]

end Firth.Exports
"""


def main() -> int:
    check = "--check" in sys.argv[1:]
    if not EXPORTER.is_file():
        print(f"missing {EXPORTER} (run `lake build` first)", file=sys.stderr)
        return 2
    pairs = load_manifest()
    wanted: dict[Path, str] = {module_path(module): export(source, module)
                               for source, module in pairs}
    wanted[EXPORTS / "All.lean"] = aggregate(pairs)
    present = {path for path in EXPORTS.rglob("*.lean")}

    drift = sorted(str(path.relative_to(ROOT)) for path, text in wanted.items()
                   if not path.is_file() or path.read_text(encoding="utf-8") != text)
    stray = sorted(str(path.relative_to(ROOT)) for path in present - set(wanted))
    if check:
        for path in drift:
            print(f"stale kernel export: {path}", file=sys.stderr)
        for path in stray:
            print(f"kernel export with no manifest entry: {path}", file=sys.stderr)
        if drift or stray:
            print("run `python3 tools/loop/update_kernel_exports.py`", file=sys.stderr)
            return 1
        if not planted_edit_detected():
            print(f"a planted edit to {PLANT_SOURCE} did not change the export of "
                  f"{PLANT_WORD}", file=sys.stderr)
            return 1
        print(f"kernel exports match their sources ({len(pairs)} modules)")
        return 0

    for path, text in wanted.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    for path in stray:
        (ROOT / path).unlink()
    print(f"wrote {len(pairs)} kernel exports and src/exports/All.lean")
    return 0


if __name__ == "__main__":
    sys.exit(main())
