import exports.Programs.Allocate
import exports.Programs.Factorial
import exports.Programs.Fib
import exports.Programs.Locals
import exports.Programs.Quotations
import exports.Programs.Sequences
import exports.Programs.Signed
import exports.Programs.SumTo
import exports.Inventory.Allocator

/-!
Generated by `python3 tools/loop/update_kernel_exports.py` from
`src/exports/manifest.json`. Do not edit.
-/

namespace Firth.Exports

/-- Every exported source: its module, its source path, and its words (name,
kernel program, body digest) in declaration order. -/
def all : List (String × String × List (String × Firth.Interpreter.Program × String)) := [
  ("Programs.Allocate", "examples/programs/allocate.firth", Firth.Exports.Programs.Allocate.words),
  ("Programs.Factorial", "examples/programs/factorial.firth", Firth.Exports.Programs.Factorial.words),
  ("Programs.Fib", "examples/programs/fib.firth", Firth.Exports.Programs.Fib.words),
  ("Programs.Locals", "examples/programs/locals.firth", Firth.Exports.Programs.Locals.words),
  ("Programs.Quotations", "examples/programs/quotations.firth", Firth.Exports.Programs.Quotations.words),
  ("Programs.Sequences", "examples/programs/sequences.firth", Firth.Exports.Programs.Sequences.words),
  ("Programs.Signed", "examples/programs/signed.firth", Firth.Exports.Programs.Signed.words),
  ("Programs.SumTo", "examples/programs/sum-to.firth", Firth.Exports.Programs.SumTo.words),
  ("Inventory.Allocator", "examples/inventory/allocator.firth", Firth.Exports.Inventory.Allocator.words)]

end Firth.Exports
