import FirthReferenceRun

/-!
Generated by `lake exe firthExportLean` from `examples/programs/allocate.firth`. Do not edit:
`python3 tools/loop/update_kernel_exports.py` regenerates it, and CI fails when
this file differs from what the elaborator produces from that source.

Each word's `body` is the erased kernel program the elaborator checked and the
compiler admitted, and `bodyDigest` is the `body_digest` of that program in the
VM image. `FirthExportsTest` lowers every `body` again and fails unless it
hashes to `bodyDigest`.

`dictionary`, `Firth.ReferenceRun.adapterGamma` and `defaultCosts` are exactly
what the reference runner executes these words with.
-/

namespace Firth.Exports.Programs.Allocate
open Firth.Interpreter
open Firth.ReferenceRun

/-- SHA-256 of the source text these definitions were generated from. -/
def sourceDigest : String := "5d4a81f6b04870aa8e67989046798d8f58db200c624a4811183f26af42bfa3d2"

namespace «over»

/-- The erased kernel program of `over`. -/
def body : Program :=
  .cons (.quotation (
    .cons .dup <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .empty

/-- The image's `body_digest` for `over`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "9f92d86a26bd41663bf5bcfc8525411fc26210bcf9800860ab913c0799a8074b"

/-- The erased word type the image records for `over`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many,v1:Int^many,v2:Int^many)"

end «over»

namespace «min»

/-- The erased kernel program of `min`. -/
def body : Program :=
  .cons (.word "over") <|
  .cons (.word "over") <|
  .cons (.prim "<") <|
  .cons (.quotation (
    .cons .drop <|
    .empty)) <|
  .cons (.quotation (
    .cons .swap <|
    .cons .drop <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `min`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "85f510b41223b7bf38d6c9f27623477e1ec2646229ac6879bfa31a7736d9b10d"

/-- The erased word type the image records for `min`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many)"

end «min»

namespace «allocate-partial»

/-- The erased kernel program of `allocate-partial`. -/
def body : Program :=
  .cons (.word "over") <|
  .cons (.word "min") <|
  .cons .dup <|
  .cons (.quotation (
    .cons (.prim "-") <|
    .empty)) <|
  .cons .dip <|
  .empty

/-- The image's `body_digest` for `allocate-partial`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "8bbb50eee18894a29f4a7f28af31a1f3b0bbfb91eb672a217dac1b42220865bf"

/-- The erased word type the image records for `allocate-partial`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many,v1:Int^many)"

end «allocate-partial»

namespace «allocate-whole»

/-- The erased kernel program of `allocate-whole`. -/
def body : Program :=
  .cons (.word "over") <|
  .cons (.word "over") <|
  .cons (.prim "<") <|
  .cons (.quotation (
    .cons .drop <|
    .cons (.lit (.int 0)) <|
    .empty)) <|
  .cons (.quotation (
    .cons .dup <|
    .cons (.quotation (
      .cons (.prim "-") <|
      .empty)) <|
    .cons .dip <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `allocate-whole`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "1d00b4ab748cc6ba1e385743a9e76faa7f1b62ac1437c146d71bb91bf6913b6d"

/-- The erased word type the image records for `allocate-whole`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many,v1:Int^many)"

end «allocate-whole»

namespace «reason»

/-- The erased kernel program of `reason`. -/
def body : Program :=
  .cons .swap <|
  .cons (.word "over") <|
  .cons (.prim "=") <|
  .cons (.quotation (
    .cons .drop <|
    .cons .drop <|
    .cons (.lit (.int 0)) <|
    .empty)) <|
  .cons (.quotation (
    .cons .dup <|
    .cons (.lit (.int 0)) <|
    .cons (.prim "=") <|
    .cons (.quotation (
      .cons .drop <|
      .cons (.lit (.int 0)) <|
      .cons (.prim "=") <|
      .cons (.quotation (
        .cons (.lit (.int 2)) <|
        .empty)) <|
      .cons (.quotation (
        .cons (.lit (.int 3)) <|
        .empty)) <|
      .cons .ifThenElse <|
      .empty)) <|
    .cons (.quotation (
      .cons .drop <|
      .cons .drop <|
      .cons (.lit (.int 1)) <|
      .empty)) <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `reason`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "8ab62ad01cc07850241b21d033593e03a654ed18d5b6f32198cad4b5307d74ca"

/-- The erased word type the image records for `reason`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Int^many--ρ,v0:Int^many)"

end «reason»

namespace «allocate»

/-- The erased kernel program of `allocate`. -/
def body : Program :=
  .cons (.quotation (
    .cons (.word "over") <|
    .cons (.word "over") <|
    .cons (.word "allocate-whole") <|
    .empty)) <|
  .cons (.quotation (
    .cons (.word "over") <|
    .cons (.word "over") <|
    .cons (.word "allocate-partial") <|
    .empty)) <|
  .cons .ifThenElse <|
  .cons .swap <|
  .cons (.quotation (
    .cons .dup <|
    .cons (.quotation (
      .cons (.word "reason") <|
      .empty)) <|
    .cons .dip <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons (.quotation (
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .empty

/-- The image's `body_digest` for `allocate`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "003ea8d3852bf8317ce624edb208ee3c6d3f54580f6f16a2fa5c500bae30f338"

/-- The erased word type the image records for `allocate`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Bool^many--ρ,v0:Int^many,v1:Int^many,v2:Int^many)"

end «allocate»

/-- Every word, in declaration order: its name, body and body digest. -/
def words : List (String × Program × String) := [
  ("over", «over».body, «over».bodyDigest),
  ("min", «min».body, «min».bodyDigest),
  ("allocate-partial", «allocate-partial».body, «allocate-partial».bodyDigest),
  ("allocate-whole", «allocate-whole».body, «allocate-whole».bodyDigest),
  ("reason", «reason».body, «reason».bodyDigest),
  ("allocate", «allocate».body, «allocate».bodyDigest)]

/-- The dictionary the reference runner builds for this source. -/
def dictionary : Dictionary
  | "over" => some { type := adapterWordType, body := «over».body }
  | "min" => some { type := adapterWordType, body := «min».body }
  | "allocate-partial" => some { type := adapterWordType, body := «allocate-partial».body }
  | "allocate-whole" => some { type := adapterWordType, body := «allocate-whole».body }
  | "reason" => some { type := adapterWordType, body := «reason».body }
  | "allocate" => some { type := adapterWordType, body := «allocate».body }
  | _ => none

end Firth.Exports.Programs.Allocate
