import FirthReferenceRun

/-!
Generated by `lake exe firthExportLean` from `examples/programs/booleans.firth`. Do not edit:
`python3 tools/loop/update_kernel_exports.py` regenerates it, and CI fails when
this file differs from what the elaborator produces from that source.

Each word's `body` is the erased kernel program the elaborator checked and the
compiler accepted, and `bodyDigest` is the `body_digest` of that program in the
VM image. `FirthExportsTest` lowers every `body` again and fails unless it
hashes to `bodyDigest`.

`dictionary`, `Firth.ReferenceRun.adapterGamma` and `defaultCosts` are exactly
what the reference runner executes these words with.
-/

namespace Firth.Exports.Programs.Booleans
open Firth.Interpreter
open Firth.ReferenceRun

/-- SHA-256 of the source text these definitions were generated from. -/
def sourceDigest : String := "380dc8df318758a63e16bd0d4c3900f0b9e2cb401f3746154ff201630250e7e3"

namespace «in-range»

/-- The erased kernel program of `in-range`. -/
def body : Program :=
  .cons (.pick 1) <|
  .cons (.roll 3) <|
  .cons (.prim "<") <|
  .cons (.prim "not") <|
  .cons (.roll 2) <|
  .cons (.roll 2) <|
  .cons (.prim "<") <|
  .cons (.prim "and") <|
  .empty

/-- The image's `body_digest` for `in-range`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "a7a079e71090f55f5a2f66a6954a398a0e2b5027a86e345b8933199ab6d5c545"

/-- The erased word type the image records for `in-range`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Int^many--ρ,v0:Bool^many)"

end «in-range»

namespace «outside»

/-- The erased kernel program of `outside`. -/
def body : Program :=
  .cons (.pick 1) <|
  .cons (.roll 3) <|
  .cons (.prim "<") <|
  .cons (.pick 1) <|
  .cons (.pick 3) <|
  .cons (.prim "<") <|
  .cons (.roll 2) <|
  .cons (.roll 3) <|
  .cons (.prim "=") <|
  .cons (.prim "or") <|
  .cons (.prim "or") <|
  .empty

/-- The image's `body_digest` for `outside`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "2265132dc0626fc4a6e57a57726f7a1422061968026e0065379d50c8c34f8929"

/-- The erased word type the image records for `outside`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Int^many--ρ,v0:Bool^many)"

end «outside»

namespace «xor»

/-- The erased kernel program of `xor`. -/
def body : Program :=
  .cons (.pick 1) <|
  .cons (.pick 1) <|
  .cons (.prim "or") <|
  .cons (.roll 2) <|
  .cons (.roll 2) <|
  .cons (.prim "and") <|
  .cons (.prim "not") <|
  .cons (.prim "and") <|
  .empty

/-- The image's `body_digest` for `xor`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "541e33e8706cc691b34cc0e7d5e8c29ac0538a89b09b6764b23a2274a7a3a6a1"

/-- The erased word type the image records for `xor`. -/
def erasedType : String := "(forallρ;ρ,v0:Bool^many,v1:Bool^many--ρ,v0:Bool^many)"

end «xor»

namespace «all-from»

/-- The erased kernel program of `all-from`. -/
def body : Program :=
  .cons .dup <|
  .cons (.pick 2) <|
  .cons (.prim "seq-bool.len") <|
  .cons (.prim "<") <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.pick 1) <|
    .cons (.pick 1) <|
    .cons (.prim "seq-bool.at") <|
    .cons (.roll 2) <|
    .cons .quote <|
    .cons (.roll 2) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons .swap <|
      .cons .swap <|
      .cons (.lit (.int 1)) <|
      .cons (.prim "+") <|
      .cons (.word "all-from") <|
      .empty)) <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.lit (.bool false)) <|
      .empty)) <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.lit (.bool true)) <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `all-from`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "a00cf0cf19067abc34e0b3f6bbb15aa90ec6c4d08f234a2d1465cdf026c40000"

/-- The erased word type the image records for `all-from`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqBool^many,v1:Int^many--ρ,v0:Bool^many)"

end «all-from»

namespace «all»

/-- The erased kernel program of `all`. -/
def body : Program :=
  .cons (.lit (.int 0)) <|
  .cons (.word "all-from") <|
  .empty

/-- The image's `body_digest` for `all`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "c3d768c2a806d5b7e07576ae7fbb0567476a4943a80cabb132777155f410b139"

/-- The erased word type the image records for `all`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqBool^many--ρ,v0:Bool^many)"

end «all»

/-- Every word, in declaration order: its name, body, body digest and erased
type. -/
def words : List (String × Program × String × String) := [
  ("in-range", «in-range».body, «in-range».bodyDigest, «in-range».erasedType),
  ("outside", «outside».body, «outside».bodyDigest, «outside».erasedType),
  ("xor", «xor».body, «xor».bodyDigest, «xor».erasedType),
  ("all-from", «all-from».body, «all-from».bodyDigest, «all-from».erasedType),
  ("all", «all».body, «all».bodyDigest, «all».erasedType)]

/-- The dictionary the reference runner builds for this source. -/
def dictionary : Dictionary
  | "in-range" => some { type := adapterWordType, body := «in-range».body }
  | "outside" => some { type := adapterWordType, body := «outside».body }
  | "xor" => some { type := adapterWordType, body := «xor».body }
  | "all-from" => some { type := adapterWordType, body := «all-from».body }
  | "all" => some { type := adapterWordType, body := «all».body }
  | _ => none

/-! Each word's dictionary entry, which a proof unfolding a call to it needs. -/

theorem «in-range».entry :
    dictionary "in-range" = some { type := adapterWordType, body := «in-range».body } := rfl

theorem «outside».entry :
    dictionary "outside" = some { type := adapterWordType, body := «outside».body } := rfl

theorem «xor».entry :
    dictionary "xor" = some { type := adapterWordType, body := «xor».body } := rfl

theorem «all-from».entry :
    dictionary "all-from" = some { type := adapterWordType, body := «all-from».body } := rfl

theorem «all».entry :
    dictionary "all" = some { type := adapterWordType, body := «all».body } := rfl

end Firth.Exports.Programs.Booleans
