import FirthReferenceRun

/-!
Generated by `lake exe firthExportLean` from `examples/programs/division.firth`. Do not edit:
`python3 tools/loop/update_kernel_exports.py` regenerates it, and CI fails when
this file differs from what the elaborator produces from that source.

Each word's `body` is the erased kernel program the elaborator checked and the
compiler accepted, and `bodyDigest` is the `body_digest` of that program in the
VM image. `FirthExportsTest` lowers every `body` again and fails unless it
hashes to `bodyDigest`.

`dictionary`, `Firth.ReferenceRun.adapterGamma` and `defaultCosts` are exactly
what the reference runner executes these words with.
-/

namespace Firth.Exports.Programs.Division
open Firth.Interpreter
open Firth.ReferenceRun

/-- SHA-256 of the source text these definitions were generated from. -/
def sourceDigest : String := "b47405afb5a12d480f4b5eee04d450fac224e32daafcee74bb6d001c0679faed"

namespace «divmod»

/-- The erased kernel program of `divmod`. -/
def body : Program :=
  .cons (.pick 1) <|
  .cons (.pick 1) <|
  .cons (.prim "div") <|
  .cons (.roll 2) <|
  .cons (.roll 2) <|
  .cons (.prim "mod") <|
  .empty

/-- The image's `body_digest` for `divmod`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "5f5542c10cc26bca94b8417cd7a59d21661b470145b45bcb5e4579f97c6b5669"

/-- The erased word type the image records for `divmod`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many,v1:Int^many)"

end «divmod»

namespace «abs»

/-- The erased kernel program of `abs`. -/
def body : Program :=
  .cons .dup <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "<") <|
  .cons (.pick 1) <|
  .cons .quote <|
  .cons (.quotation (
    .cons (.lit (.int 0)) <|
    .cons .swap <|
    .cons (.prim "-") <|
    .empty)) <|
  .cons .compose <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons (.quotation (.empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `abs`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "472591df6d2517e379b8604d7a3a522f79a99deb3df8f0436edce970f7eadb09"

/-- The erased word type the image records for `abs`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many--ρ,v0:Int^many)"

end «abs»

namespace «digit-sum-from»

/-- The erased kernel program of `digit-sum-from`. -/
def body : Program :=
  .cons (.pick 1) <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "=") <|
  .cons (.pick 1) <|
  .cons .quote <|
  .cons (.quotation (.empty)) <|
  .cons .compose <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.pick 1) <|
    .cons (.lit (.int 10)) <|
    .cons (.prim "div") <|
    .cons .swap <|
    .cons (.roll 2) <|
    .cons (.lit (.int 10)) <|
    .cons (.prim "mod") <|
    .cons (.prim "+") <|
    .cons (.word "digit-sum-from") <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `digit-sum-from`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "0d87c3583e3faa7ed3d97ce8621ad6cf7375b269f24206ee4bd021a03f8cbfdb"

/-- The erased word type the image records for `digit-sum-from`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many)"

end «digit-sum-from»

namespace «digit-sum»

/-- The erased kernel program of `digit-sum`. -/
def body : Program :=
  .cons (.word "abs") <|
  .cons (.lit (.int 0)) <|
  .cons (.word "digit-sum-from") <|
  .empty

/-- The image's `body_digest` for `digit-sum`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "b76fe2fdac488cf3ffbbfbbb64f0f1b967c98f0f8be7bdb2fd82d9c1ae54fe2b"

/-- The erased word type the image records for `digit-sum`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many--ρ,v0:Int^many)"

end «digit-sum»

namespace «gcd»

/-- The erased kernel program of `gcd`. -/
def body : Program :=
  .cons .dup <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "=") <|
  .cons (.pick 2) <|
  .cons .quote <|
  .cons (.quotation (
    .cons (.word "abs") <|
    .empty)) <|
  .cons .compose <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.pick 1) <|
    .cons .swap <|
    .cons (.roll 2) <|
    .cons (.prim "mod") <|
    .cons (.word "gcd") <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `gcd`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "b1d8e39c2215f534b05b84f7df4fdce4fd1e3664f4df4d2f942e48597f571f31"

/-- The erased word type the image records for `gcd`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many)"

end «gcd»

/-- Every word, in declaration order: its name, body, body digest and erased
type. -/
def words : List (String × Program × String × String) := [
  ("divmod", «divmod».body, «divmod».bodyDigest, «divmod».erasedType),
  ("abs", «abs».body, «abs».bodyDigest, «abs».erasedType),
  ("digit-sum-from", «digit-sum-from».body, «digit-sum-from».bodyDigest, «digit-sum-from».erasedType),
  ("digit-sum", «digit-sum».body, «digit-sum».bodyDigest, «digit-sum».erasedType),
  ("gcd", «gcd».body, «gcd».bodyDigest, «gcd».erasedType)]

/-- The dictionary the reference runner builds for this source. -/
def dictionary : Dictionary
  | "divmod" => some { type := adapterWordType, body := «divmod».body }
  | "abs" => some { type := adapterWordType, body := «abs».body }
  | "digit-sum-from" => some { type := adapterWordType, body := «digit-sum-from».body }
  | "digit-sum" => some { type := adapterWordType, body := «digit-sum».body }
  | "gcd" => some { type := adapterWordType, body := «gcd».body }
  | _ => none

/-! Each word's dictionary entry, which a proof unfolding a call to it needs. -/

theorem «divmod».entry :
    dictionary "divmod" = some { type := adapterWordType, body := «divmod».body } := rfl

theorem «abs».entry :
    dictionary "abs" = some { type := adapterWordType, body := «abs».body } := rfl

theorem «digit-sum-from».entry :
    dictionary "digit-sum-from" = some { type := adapterWordType, body := «digit-sum-from».body } := rfl

theorem «digit-sum».entry :
    dictionary "digit-sum" = some { type := adapterWordType, body := «digit-sum».body } := rfl

theorem «gcd».entry :
    dictionary "gcd" = some { type := adapterWordType, body := «gcd».body } := rfl

end Firth.Exports.Programs.Division
