import FirthReferenceRun

/-!
Generated by `lake exe firthExportLean` from `examples/programs/factorial.firth`. Do not edit:
`python3 tools/loop/update_kernel_exports.py` regenerates it, and CI fails when
this file differs from what the elaborator produces from that source.

Each word's `body` is the erased kernel program the elaborator checked and the
compiler admitted, and `bodyDigest` is the `body_digest` of that program in the
VM image. `FirthExportsTest` lowers every `body` again and fails unless it
hashes to `bodyDigest`.

`dictionary`, `Firth.ReferenceRun.adapterGamma` and `defaultCosts` are exactly
what the reference runner executes these words with.
-/

namespace Firth.Exports.Programs.Factorial
open Firth.Interpreter
open Firth.ReferenceRun

/-- SHA-256 of the source text these definitions were generated from. -/
def sourceDigest : String := "20d7b7befda7deae19b84fc7240016fffefa6a8ffb8b468faa4122350a3d44ac"

namespace «fact»

/-- The erased kernel program of `fact`. -/
def body : Program :=
  .cons (.lit (.int 1)) <|
  .cons .swap <|
  .cons (.word "fact-acc") <|
  .empty

/-- The image's `body_digest` for `fact`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "62e25e6cc26e034dde258375d1f5109164ba32521c7147a9af28636c6e97a85b"

/-- The erased word type the image records for `fact`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many--ρ,v0:Int^many)"

end «fact»

namespace «fact-acc»

/-- The erased kernel program of `fact-acc`. -/
def body : Program :=
  .cons .dup <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "=") <|
  .cons (.quotation (
    .cons .drop <|
    .empty)) <|
  .cons (.quotation (
    .cons .dup <|
    .cons (.lit (.int 1)) <|
    .cons (.prim "-") <|
    .cons (.quotation (
      .cons (.prim "*") <|
      .empty)) <|
    .cons .dip <|
    .cons (.word "fact-acc") <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `fact-acc`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "f9d4217abf8c69c5b7f7536a88890867a42070e99d417a3a56d2ff9f7db5b825"

/-- The erased word type the image records for `fact-acc`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many)"

end «fact-acc»

/-- Every word, in declaration order: its name, body and body digest. -/
def words : List (String × Program × String) := [
  ("fact", «fact».body, «fact».bodyDigest),
  ("fact-acc", «fact-acc».body, «fact-acc».bodyDigest)]

/-- The dictionary the reference runner builds for this source. -/
def dictionary : Dictionary
  | "fact" => some { type := adapterWordType, body := «fact».body }
  | "fact-acc" => some { type := adapterWordType, body := «fact-acc».body }
  | _ => none

end Firth.Exports.Programs.Factorial
