import FirthReferenceRun

/-!
Generated by `lake exe firthExportLean` from `examples/programs/fib.firth`. Do not edit:
`python3 tools/loop/update_kernel_exports.py` regenerates it, and CI fails when
this file differs from what the elaborator produces from that source.

Each word's `body` is the erased kernel program the elaborator checked and the
compiler accepted, and `bodyDigest` is the `body_digest` of that program in the
VM image. `FirthExportsTest` lowers every `body` again and fails unless it
hashes to `bodyDigest`.

`dictionary`, `Firth.ReferenceRun.adapterGamma` and `defaultCosts` are exactly
what the reference runner executes these words with.
-/

namespace Firth.Exports.Programs.Fib
open Firth.Interpreter
open Firth.ReferenceRun

/-- SHA-256 of the source text these definitions were generated from. -/
def sourceDigest : String := "ef20e3650b33754e010411c27ec03ae80f5f57d73e7fc18dc36e142d49180ae2"

namespace «fib»

/-- The erased kernel program of `fib`. -/
def body : Program :=
  .cons (.lit (.int 0)) <|
  .cons .swap <|
  .cons (.lit (.int 1)) <|
  .cons .swap <|
  .cons (.word "fib-loop") <|
  .empty

/-- The image's `body_digest` for `fib`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "95359a39588c7e61d8b54eed51c0eb528dac81f191f916200b1684b71f2a39aa"

/-- The erased word type the image records for `fib`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many--ρ,v0:Int^many)"

end «fib»

namespace «fib-loop»

/-- The erased kernel program of `fib-loop`. -/
def body : Program :=
  .cons .dup <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "=") <|
  .cons (.quotation (
    .cons .drop <|
    .cons .drop <|
    .empty)) <|
  .cons (.quotation (
    .cons (.lit (.int 1)) <|
    .cons (.prim "-") <|
    .cons (.quotation (
      .cons .dup <|
      .cons (.quotation (
        .cons (.prim "+") <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons (.word "fib-loop") <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `fib-loop`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "1a19664bb3ff19b82a203367ae9004f063d8ba79a0d1a1047f4a22cbc4d21eb4"

/-- The erased word type the image records for `fib-loop`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Int^many--ρ,v0:Int^many)"

end «fib-loop»

/-- Every word, in declaration order: its name, body, body digest and erased
type. -/
def words : List (String × Program × String × String) := [
  ("fib", «fib».body, «fib».bodyDigest, «fib».erasedType),
  ("fib-loop", «fib-loop».body, «fib-loop».bodyDigest, «fib-loop».erasedType)]

/-- The dictionary the reference runner builds for this source. -/
def dictionary : Dictionary
  | "fib" => some { type := adapterWordType, body := «fib».body }
  | "fib-loop" => some { type := adapterWordType, body := «fib-loop».body }
  | _ => none

/-! Each word's dictionary entry, which a proof unfolding a call to it needs. -/

theorem «fib».entry :
    dictionary "fib" = some { type := adapterWordType, body := «fib».body } := rfl

theorem «fib-loop».entry :
    dictionary "fib-loop" = some { type := adapterWordType, body := «fib-loop».body } := rfl

end Firth.Exports.Programs.Fib
