import FirthReferenceRun

/-!
Generated by `lake exe firthExportLean` from `examples/programs/locals.firth`. Do not edit:
`python3 tools/loop/update_kernel_exports.py` regenerates it, and CI fails when
this file differs from what the elaborator produces from that source.

Each word's `body` is the erased kernel program the elaborator checked and the
compiler accepted, and `bodyDigest` is the `body_digest` of that program in the
VM image. `FirthExportsTest` lowers every `body` again and fails unless it
hashes to `bodyDigest`.

`dictionary`, `Firth.ReferenceRun.adapterGamma` and `defaultCosts` are exactly
what the reference runner executes these words with.
-/

namespace Firth.Exports.Programs.Locals
open Firth.Interpreter
open Firth.ReferenceRun

/-- SHA-256 of the source text these definitions were generated from. -/
def sourceDigest : String := "e8b3b77a63e41ea9491a985fc97c6d73b333ffc252fcddcc1abc0125e3f7804e"

namespace «fact»

/-- The erased kernel program of `fact`. -/
def body : Program :=
  .cons .dup <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "=") <|
  .cons (.quotation (
    .cons (.lit (.int 1)) <|
    .empty)) <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons (.quotation (
    .cons .dup <|
    .cons (.lit (.int 1)) <|
    .cons (.prim "-") <|
    .cons (.word "fact") <|
    .cons .swap <|
    .cons (.prim "*") <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `fact`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "e71a2fd4091d9177bedb2fdd4752041773af817993add50fd619397599419ee6"

/-- The erased word type the image records for `fact`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many--ρ,v0:Int^many)"

end «fact»

namespace «fib-loop»

/-- The erased kernel program of `fib-loop`. -/
def body : Program :=
  .cons .dup <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "=") <|
  .cons (.pick 3) <|
  .cons .quote <|
  .cons (.quotation (.empty)) <|
  .cons .compose <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons (.roll 4) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.pick 2) <|
    .cons (.roll 2) <|
    .cons (.roll 3) <|
    .cons (.prim "+") <|
    .cons (.roll 2) <|
    .cons (.lit (.int 1)) <|
    .cons (.prim "-") <|
    .cons (.word "fib-loop") <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `fib-loop`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "29401bc6933cc046ea2904fa0c6af33656dd76fee361844308525fb834a18a55"

/-- The erased word type the image records for `fib-loop`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Int^many--ρ,v0:Int^many)"

end «fib-loop»

namespace «fib»

/-- The erased kernel program of `fib`. -/
def body : Program :=
  .cons (.lit (.int 0)) <|
  .cons (.lit (.int 1)) <|
  .cons (.roll 2) <|
  .cons (.word "fib-loop") <|
  .empty

/-- The image's `body_digest` for `fib`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "d5c046984b9b65877e14450005ecb051cfa8691d88c985561d76d84db361a1fc"

/-- The erased word type the image records for `fib`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many--ρ,v0:Int^many)"

end «fib»

namespace «allocate-partial»

/-- The erased kernel program of `allocate-partial`. -/
def body : Program :=
  .cons (.pick 1) <|
  .cons (.pick 1) <|
  .cons (.prim "<") <|
  .cons (.pick 2) <|
  .cons .quote <|
  .cons (.quotation (
    .cons (.lit (.int 0)) <|
    .cons .swap <|
    .empty)) <|
  .cons .compose <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons .swap <|
    .cons (.pick 1) <|
    .cons (.prim "-") <|
    .cons .swap <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `allocate-partial`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "a07db3e466572f40592b6a7b4510cd71510606d6c41a7e3ad938cbebd35c0c15"

/-- The erased word type the image records for `allocate-partial`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many,v1:Int^many)"

end «allocate-partial»

namespace «sort3»

/-- The erased kernel program of `sort3`. -/
def body : Program :=
  .cons (.pick 2) <|
  .cons (.pick 2) <|
  .cons (.prim "<") <|
  .cons (.pick 2) <|
  .cons .quote <|
  .cons (.pick 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.pick 4) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.pick 2) <|
    .cons (.pick 2) <|
    .cons (.prim "<") <|
    .cons (.pick 1) <|
    .cons .quote <|
    .cons (.pick 4) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.pick 3) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.roll 2) <|
      .cons (.roll 2) <|
      .cons (.roll 2) <|
      .empty)) <|
    .cons .compose <|
    .cons (.roll 2) <|
    .cons .quote <|
    .cons (.roll 3) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.roll 3) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.pick 2) <|
      .cons (.pick 2) <|
      .cons (.prim "<") <|
      .cons (.pick 3) <|
      .cons .quote <|
      .cons (.pick 3) <|
      .cons .quote <|
      .cons .compose <|
      .cons (.pick 2) <|
      .cons .quote <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.roll 2) <|
        .cons (.roll 2) <|
        .cons (.roll 2) <|
        .empty)) <|
      .cons .compose <|
      .cons (.roll 3) <|
      .cons .quote <|
      .cons (.roll 4) <|
      .cons .quote <|
      .cons .compose <|
      .cons (.roll 3) <|
      .cons .quote <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.roll 2) <|
        .cons (.roll 2) <|
        .cons (.roll 2) <|
        .empty)) <|
      .cons .compose <|
      .cons .ifThenElse <|
      .empty)) <|
    .cons .compose <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons (.roll 4) <|
  .cons .quote <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.pick 2) <|
    .cons (.pick 2) <|
    .cons (.prim "<") <|
    .cons (.pick 1) <|
    .cons .quote <|
    .cons (.pick 4) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.pick 3) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.roll 2) <|
      .cons (.roll 2) <|
      .cons (.roll 2) <|
      .empty)) <|
    .cons .compose <|
    .cons (.roll 2) <|
    .cons .quote <|
    .cons (.roll 3) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.roll 3) <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.pick 2) <|
      .cons (.pick 2) <|
      .cons (.prim "<") <|
      .cons (.pick 3) <|
      .cons .quote <|
      .cons (.pick 3) <|
      .cons .quote <|
      .cons .compose <|
      .cons (.pick 2) <|
      .cons .quote <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.roll 2) <|
        .cons (.roll 2) <|
        .cons (.roll 2) <|
        .empty)) <|
      .cons .compose <|
      .cons (.roll 3) <|
      .cons .quote <|
      .cons (.roll 4) <|
      .cons .quote <|
      .cons .compose <|
      .cons (.roll 3) <|
      .cons .quote <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.roll 2) <|
        .cons (.roll 2) <|
        .cons (.roll 2) <|
        .empty)) <|
      .cons .compose <|
      .cons .ifThenElse <|
      .empty)) <|
    .cons .compose <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `sort3`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "cd13e2f0a05197f77ee55ca17359123acdfd62d1ffcec4f72e273c376f7403ac"

/-- The erased word type the image records for `sort3`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Int^many--ρ,v0:Int^many,v1:Int^many,v2:Int^many)"

end «sort3»

namespace «swap-below»

/-- The erased kernel program of `swap-below`. -/
def body : Program :=
  .cons (.quotation (
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .drop <|
  .empty

/-- The image's `body_digest` for `swap-below`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "e2df75b0b3efcb5cd8f6e5436f5ac9622662c41bc84003a1521f2e52768892c4"

/-- The erased word type the image records for `swap-below`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Int^many--ρ,v0:Int^many,v1:Int^many)"

end «swap-below»

/-- Every word, in declaration order: its name, body and body digest. -/
def words : List (String × Program × String) := [
  ("fact", «fact».body, «fact».bodyDigest),
  ("fib-loop", «fib-loop».body, «fib-loop».bodyDigest),
  ("fib", «fib».body, «fib».bodyDigest),
  ("allocate-partial", «allocate-partial».body, «allocate-partial».bodyDigest),
  ("sort3", «sort3».body, «sort3».bodyDigest),
  ("swap-below", «swap-below».body, «swap-below».bodyDigest)]

/-- The dictionary the reference runner builds for this source. -/
def dictionary : Dictionary
  | "fact" => some { type := adapterWordType, body := «fact».body }
  | "fib-loop" => some { type := adapterWordType, body := «fib-loop».body }
  | "fib" => some { type := adapterWordType, body := «fib».body }
  | "allocate-partial" => some { type := adapterWordType, body := «allocate-partial».body }
  | "sort3" => some { type := adapterWordType, body := «sort3».body }
  | "swap-below" => some { type := adapterWordType, body := «swap-below».body }
  | _ => none

/-! Each word's dictionary entry, which a proof unfolding a call to it needs. -/

theorem «fact».entry :
    dictionary "fact" = some { type := adapterWordType, body := «fact».body } := rfl

theorem «fib-loop».entry :
    dictionary "fib-loop" = some { type := adapterWordType, body := «fib-loop».body } := rfl

theorem «fib».entry :
    dictionary "fib" = some { type := adapterWordType, body := «fib».body } := rfl

theorem «allocate-partial».entry :
    dictionary "allocate-partial" = some { type := adapterWordType, body := «allocate-partial».body } := rfl

theorem «sort3».entry :
    dictionary "sort3" = some { type := adapterWordType, body := «sort3».body } := rfl

theorem «swap-below».entry :
    dictionary "swap-below" = some { type := adapterWordType, body := «swap-below».body } := rfl

end Firth.Exports.Programs.Locals
