import FirthReferenceRun

/-!
Generated by `lake exe firthExportLean` from `examples/programs/locals.firth`. Do not edit:
`python3 tools/loop/update_kernel_exports.py` regenerates it, and CI fails when
this file differs from what the elaborator produces from that source.

Each word's `body` is the erased kernel program the elaborator checked and the
compiler admitted, and `bodyDigest` is the `body_digest` of that program in the
VM image. `FirthExportsTest` lowers every `body` again and fails unless it
hashes to `bodyDigest`.

`dictionary`, `Firth.ReferenceRun.adapterGamma` and `defaultCosts` are exactly
what the reference runner executes these words with.
-/

namespace Firth.Exports.Programs.Locals
open Firth.Interpreter
open Firth.ReferenceRun

/-- SHA-256 of the source text these definitions were generated from. -/
def sourceDigest : String := "e8b3b77a63e41ea9491a985fc97c6d73b333ffc252fcddcc1abc0125e3f7804e"

namespace «fact»

/-- The erased kernel program of `fact`. -/
def body : Program :=
  .cons .dup <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "=") <|
  .cons (.quotation (
    .cons (.lit (.int 1)) <|
    .empty)) <|
  .cons (.quotation (
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons (.quotation (
    .cons .dup <|
    .cons (.lit (.int 1)) <|
    .cons (.prim "-") <|
    .cons (.word "fact") <|
    .cons .swap <|
    .cons (.prim "*") <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `fact`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "668a4d0578a92d4656ff3b2567174908a0f166bfcf5e42b3e1c2e710045f5195"

/-- The erased word type the image records for `fact`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many--ρ,v0:Int^many)"

end «fact»

namespace «fib-loop»

/-- The erased kernel program of `fib-loop`. -/
def body : Program :=
  .cons .dup <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "=") <|
  .cons (.quotation (
    .cons (.quotation (
      .cons (.quotation (
        .cons .dup <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .empty)) <|
  .cons .dip <|
  .cons (.quotation (
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons (.quotation (.empty)) <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons (.quotation (
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.quotation (
      .cons (.quotation (
        .cons .dup <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons (.prim "+") <|
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons (.lit (.int 1)) <|
    .cons (.prim "-") <|
    .cons (.word "fib-loop") <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `fib-loop`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "3c8cddc5b6cf1654bafe6906183ec0ae7190b57022f518324733acbbf3e46d68"

/-- The erased word type the image records for `fib-loop`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Int^many--ρ,v0:Int^many)"

end «fib-loop»

namespace «fib»

/-- The erased kernel program of `fib`. -/
def body : Program :=
  .cons (.lit (.int 0)) <|
  .cons (.lit (.int 1)) <|
  .cons (.quotation (
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons (.word "fib-loop") <|
  .empty

/-- The image's `body_digest` for `fib`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "386b3435f154aff90b870eb0509520504a1050c856f2d0cbc0399f887ad93a1d"

/-- The erased word type the image records for `fib`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many--ρ,v0:Int^many)"

end «fib»

namespace «allocate-partial»

/-- The erased kernel program of `allocate-partial`. -/
def body : Program :=
  .cons (.quotation (
    .cons .dup <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons (.quotation (
    .cons .dup <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons (.prim "<") <|
  .cons (.quotation (
    .cons (.quotation (
      .cons .dup <|
      .empty)) <|
    .cons .dip <|
    .empty)) <|
  .cons .dip <|
  .cons (.quotation (
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons (.quotation (
    .cons (.lit (.int 0)) <|
    .cons .swap <|
    .empty)) <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons (.quotation (
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons .swap <|
    .cons (.quotation (
      .cons .dup <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons (.prim "-") <|
    .cons .swap <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `allocate-partial`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "aec82258c8285d2378b5d9480712f6316c358fbf2ff786f75b026d057cae7971"

/-- The erased word type the image records for `allocate-partial`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many,v1:Int^many)"

end «allocate-partial»

namespace «sort3»

/-- The erased kernel program of `sort3`. -/
def body : Program :=
  .cons (.quotation (
    .cons (.quotation (
      .cons .dup <|
      .empty)) <|
    .cons .dip <|
    .empty)) <|
  .cons .dip <|
  .cons (.quotation (
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons (.quotation (
    .cons (.quotation (
      .cons .dup <|
      .empty)) <|
    .cons .dip <|
    .empty)) <|
  .cons .dip <|
  .cons (.quotation (
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons (.prim "<") <|
  .cons (.quotation (
    .cons (.quotation (
      .cons .dup <|
      .empty)) <|
    .cons .dip <|
    .empty)) <|
  .cons .dip <|
  .cons (.quotation (
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons (.quotation (
    .cons (.quotation (
      .cons .dup <|
      .empty)) <|
    .cons .dip <|
    .empty)) <|
  .cons .dip <|
  .cons (.quotation (
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.quotation (
      .cons (.quotation (
        .cons (.quotation (
          .cons .dup <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .empty)) <|
  .cons .dip <|
  .cons (.quotation (
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.quotation (
      .cons (.quotation (
        .cons .dup <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .dup <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons (.prim "<") <|
    .cons (.quotation (
      .cons .dup <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons (.quotation (
      .cons (.quotation (
        .cons (.quotation (
          .cons (.quotation (
            .cons .dup <|
            .empty)) <|
          .cons .dip <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .cons (.quotation (
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.quotation (
        .cons (.quotation (
          .cons .dup <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .compose <|
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.quotation (
        .cons (.quotation (
          .cons .dup <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .dup <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons (.prim "<") <|
      .cons (.quotation (
        .cons (.quotation (
          .cons (.quotation (
            .cons .dup <|
            .empty)) <|
          .cons .dip <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons .quote <|
      .cons (.quotation (
        .cons (.quotation (
          .cons (.quotation (
            .cons .dup <|
            .empty)) <|
          .cons .dip <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons .quote <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .dup <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons .quote <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons .quote <|
      .cons (.quotation (
        .cons (.quotation (
          .cons (.quotation (
            .cons .swap <|
            .empty)) <|
          .cons .dip <|
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons .quote <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons .quote <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .compose <|
      .cons .ifThenElse <|
      .empty)) <|
    .cons .compose <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons (.quotation (
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.quotation (
      .cons (.quotation (
        .cons .dup <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .dup <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons (.prim "<") <|
    .cons (.quotation (
      .cons .dup <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons (.quotation (
      .cons (.quotation (
        .cons (.quotation (
          .cons (.quotation (
            .cons .dup <|
            .empty)) <|
          .cons .dip <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .cons (.quotation (
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.quotation (
        .cons (.quotation (
          .cons .dup <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .compose <|
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.quotation (
        .cons (.quotation (
          .cons .dup <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .dup <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons (.prim "<") <|
      .cons (.quotation (
        .cons (.quotation (
          .cons (.quotation (
            .cons .dup <|
            .empty)) <|
          .cons .dip <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons .quote <|
      .cons (.quotation (
        .cons (.quotation (
          .cons (.quotation (
            .cons .dup <|
            .empty)) <|
          .cons .dip <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons .quote <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .dup <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons .quote <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons .quote <|
      .cons (.quotation (
        .cons (.quotation (
          .cons (.quotation (
            .cons .swap <|
            .empty)) <|
          .cons .dip <|
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons .quote <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .cons .quote <|
      .cons .compose <|
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .compose <|
      .cons .ifThenElse <|
      .empty)) <|
    .cons .compose <|
    .cons .ifThenElse <|
    .empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `sort3`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "af6622f2763304a3fb79402c6f8d47e31bbf9984be777e19c6d6953617f3b4fc"

/-- The erased word type the image records for `sort3`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Int^many--ρ,v0:Int^many,v1:Int^many,v2:Int^many)"

end «sort3»

namespace «swap-below»

/-- The erased kernel program of `swap-below`. -/
def body : Program :=
  .cons (.quotation (
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .drop <|
  .empty

/-- The image's `body_digest` for `swap-below`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "e2df75b0b3efcb5cd8f6e5436f5ac9622662c41bc84003a1521f2e52768892c4"

/-- The erased word type the image records for `swap-below`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Int^many--ρ,v0:Int^many,v1:Int^many)"

end «swap-below»

/-- Every word, in declaration order: its name, body and body digest. -/
def words : List (String × Program × String) := [
  ("fact", «fact».body, «fact».bodyDigest),
  ("fib-loop", «fib-loop».body, «fib-loop».bodyDigest),
  ("fib", «fib».body, «fib».bodyDigest),
  ("allocate-partial", «allocate-partial».body, «allocate-partial».bodyDigest),
  ("sort3", «sort3».body, «sort3».bodyDigest),
  ("swap-below", «swap-below».body, «swap-below».bodyDigest)]

/-- The dictionary the reference runner builds for this source. -/
def dictionary : Dictionary
  | "fact" => some { type := adapterWordType, body := «fact».body }
  | "fib-loop" => some { type := adapterWordType, body := «fib-loop».body }
  | "fib" => some { type := adapterWordType, body := «fib».body }
  | "allocate-partial" => some { type := adapterWordType, body := «allocate-partial».body }
  | "sort3" => some { type := adapterWordType, body := «sort3».body }
  | "swap-below" => some { type := adapterWordType, body := «swap-below».body }
  | _ => none

end Firth.Exports.Programs.Locals
