import FirthReferenceRun

/-!
Generated by `lake exe firthExportLean` from `examples/programs/quotations.firth`. Do not edit:
`python3 tools/loop/update_kernel_exports.py` regenerates it, and CI fails when
this file differs from what the elaborator produces from that source.

Each word's `body` is the erased kernel program the elaborator checked and the
compiler accepted, and `bodyDigest` is the `body_digest` of that program in the
VM image. `FirthExportsTest` lowers every `body` again and fails unless it
hashes to `bodyDigest`.

`dictionary`, `Firth.ReferenceRun.adapterGamma` and `defaultCosts` are exactly
what the reference runner executes these words with.
-/

namespace Firth.Exports.Programs.Quotations
open Firth.Interpreter
open Firth.ReferenceRun

/-- SHA-256 of the source text these definitions were generated from. -/
def sourceDigest : String := "e688c8f22dd1815d45c2692f89390dc80a55ffb1935a4d59433781cc313b1f47"

namespace «call-then-local»

/-- The erased kernel program of `call-then-local`. -/
def body : Program :=
  .cons .swap <|
  .cons (.quotation (
    .cons (.lit (.int 1)) <|
    .cons (.prim "+") <|
    .empty)) <|
  .cons .call <|
  .cons .swap <|
  .cons (.prim "-") <|
  .empty

/-- The image's `body_digest` for `call-then-local`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "b9ec2932cf70feccbd34237c008d87d2db48c2ba9ba2438662fd4328533c1e44"

/-- The erased word type the image records for `call-then-local`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Int^many--ρ,v0:Int^many,v1:Int^many)"

end «call-then-local»

namespace «compose-then-local»

/-- The erased kernel program of `compose-then-local`. -/
def body : Program :=
  .cons .swap <|
  .cons (.quotation (
    .cons (.lit (.int 1)) <|
    .cons (.prim "+") <|
    .empty)) <|
  .cons (.quotation (.empty)) <|
  .cons .compose <|
  .cons .call <|
  .cons .swap <|
  .cons (.prim "-") <|
  .empty

/-- The image's `body_digest` for `compose-then-local`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "c7ec33cdd786ce2af5f12f240bddc0eff0fc869836ea622ef55c0033ec925e28"

/-- The erased word type the image records for `compose-then-local`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Int^many--ρ,v0:Int^many,v1:Int^many)"

end «compose-then-local»

namespace «add-step-twice»

/-- The erased kernel program of `add-step-twice`. -/
def body : Program :=
  .cons .swap <|
  .cons .swap <|
  .cons .quote <|
  .cons (.quotation (
    .cons .swap <|
    .cons (.pick 1) <|
    .cons (.prim "+") <|
    .cons .swap <|
    .cons .drop <|
    .empty)) <|
  .cons .compose <|
  .cons .dup <|
  .cons .compose <|
  .cons .call <|
  .empty

/-- The image's `body_digest` for `add-step-twice`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "25247d243986594f17d2e833911c187c9b94c1fc59d7a9da7db227a2e2a98b1b"

/-- The erased word type the image records for `add-step-twice`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many)"

end «add-step-twice»

namespace «dup-dip-then-local»

/-- The erased kernel program of `dup-dip-then-local`. -/
def body : Program :=
  .cons .swap <|
  .cons (.lit (.int 1)) <|
  .cons (.quotation (
    .cons .dup <|
    .cons (.quotation (
      .cons (.prim "+") <|
      .empty)) <|
    .cons .dip <|
    .cons .drop <|
    .empty)) <|
  .cons .call <|
  .cons .swap <|
  .cons (.prim "-") <|
  .empty

/-- The image's `body_digest` for `dup-dip-then-local`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "52ead388d013ec17bcd8fdfcd7db7a5c501b6caae3df760e9cb2c3a3becbc021"

/-- The erased word type the image records for `dup-dip-then-local`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many,v2:Int^many--ρ,v0:Int^many,v1:Int^many)"

end «dup-dip-then-local»

/-- Every word, in declaration order: its name, body, body digest and erased
type. -/
def words : List (String × Program × String × String) := [
  ("call-then-local", «call-then-local».body, «call-then-local».bodyDigest, «call-then-local».erasedType),
  ("compose-then-local", «compose-then-local».body, «compose-then-local».bodyDigest, «compose-then-local».erasedType),
  ("add-step-twice", «add-step-twice».body, «add-step-twice».bodyDigest, «add-step-twice».erasedType),
  ("dup-dip-then-local", «dup-dip-then-local».body, «dup-dip-then-local».bodyDigest, «dup-dip-then-local».erasedType)]

/-- The dictionary the reference runner builds for this source. -/
def dictionary : Dictionary
  | "call-then-local" => some { type := adapterWordType, body := «call-then-local».body }
  | "compose-then-local" => some { type := adapterWordType, body := «compose-then-local».body }
  | "add-step-twice" => some { type := adapterWordType, body := «add-step-twice».body }
  | "dup-dip-then-local" => some { type := adapterWordType, body := «dup-dip-then-local».body }
  | _ => none

/-! Each word's dictionary entry, which a proof unfolding a call to it needs. -/

theorem «call-then-local».entry :
    dictionary "call-then-local" = some { type := adapterWordType, body := «call-then-local».body } := rfl

theorem «compose-then-local».entry :
    dictionary "compose-then-local" = some { type := adapterWordType, body := «compose-then-local».body } := rfl

theorem «add-step-twice».entry :
    dictionary "add-step-twice" = some { type := adapterWordType, body := «add-step-twice».body } := rfl

theorem «dup-dip-then-local».entry :
    dictionary "dup-dip-then-local" = some { type := adapterWordType, body := «dup-dip-then-local».body } := rfl

end Firth.Exports.Programs.Quotations
