import FirthReferenceRun

/-!
Generated by `lake exe firthExportLean` from `examples/programs/sequences.firth`. Do not edit:
`python3 tools/loop/update_kernel_exports.py` regenerates it, and CI fails when
this file differs from what the elaborator produces from that source.

Each word's `body` is the erased kernel program the elaborator checked and the
compiler accepted, and `bodyDigest` is the `body_digest` of that program in the
VM image. `FirthExportsTest` lowers every `body` again and fails unless it
hashes to `bodyDigest`.

`dictionary`, `Firth.ReferenceRun.adapterGamma` and `defaultCosts` are exactly
what the reference runner executes these words with.
-/

namespace Firth.Exports.Programs.Sequences
open Firth.Interpreter
open Firth.ReferenceRun

/-- SHA-256 of the source text these definitions were generated from. -/
def sourceDigest : String := "427f33a5a998cf5defca5e4155d96eb33933a1f1659bd3b674ba026649031ac6"

namespace «sum-from»

/-- The erased kernel program of `sum-from`. -/
def body : Program :=
  .cons .dup <|
  .cons (.pick 3) <|
  .cons (.prim "seq-int.len") <|
  .cons (.prim "<") <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons (.pick 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.pick 2) <|
    .cons (.roll 2) <|
    .cons (.roll 3) <|
    .cons (.pick 3) <|
    .cons (.prim "seq-int.at") <|
    .cons (.prim "+") <|
    .cons (.roll 2) <|
    .cons (.lit (.int 1)) <|
    .cons (.prim "+") <|
    .cons (.word "sum-from") <|
    .empty)) <|
  .cons .compose <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons (.quotation (.empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `sum-from`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "244b8415af26b25000b32d0173fe6433e9765966aee77b2959c693a6b4f41e99"

/-- The erased word type the image records for `sum-from`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many,v2:Int^many--ρ,v0:Int^many)"

end «sum-from»

namespace «sum»

/-- The erased kernel program of `sum`. -/
def body : Program :=
  .cons (.lit (.int 0)) <|
  .cons (.lit (.int 0)) <|
  .cons (.word "sum-from") <|
  .empty

/-- The image's `body_digest` for `sum`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "f596758158828a459e4e181c5b0018d72f7ba43c7acaafd58b91028b6cd2af00"

/-- The erased word type the image records for `sum`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many--ρ,v0:Int^many)"

end «sum»

namespace «range-from»

/-- The erased kernel program of `range-from`. -/
def body : Program :=
  .cons (.pick 1) <|
  .cons (.pick 1) <|
  .cons (.prim "<") <|
  .cons (.pick 3) <|
  .cons .quote <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.roll 2) <|
    .cons (.pick 2) <|
    .cons (.prim "seq-int.push") <|
    .cons (.roll 2) <|
    .cons (.lit (.int 1)) <|
    .cons (.prim "+") <|
    .cons (.roll 2) <|
    .cons (.word "range-from") <|
    .empty)) <|
  .cons .compose <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons (.quotation (.empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `range-from`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "70b3c80d3afd4d04ac32964499e06559f14fc59ff9fc4d7397347d30f7f22b5c"

/-- The erased word type the image records for `range-from`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many,v2:Int^many--ρ,v0:SeqInt^many)"

end «range-from»

namespace «range»

/-- The erased kernel program of `range`. -/
def body : Program :=
  .cons (.quotation (
    .cons (.prim "seq-int.empty") <|
    .empty)) <|
  .cons .dip <|
  .cons (.lit (.int 0)) <|
  .cons .swap <|
  .cons (.word "range-from") <|
  .empty

/-- The image's `body_digest` for `range`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "fcaecdf6a47ab88f7622284d09883f068e35b46013362cfac286c5fb72328f83"

/-- The erased word type the image records for `range`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many--ρ,v0:SeqInt^many)"

end «range»

namespace «count-from»

/-- The erased kernel program of `count-from`. -/
def body : Program :=
  .cons .dup <|
  .cons (.pick 3) <|
  .cons (.prim "seq-bool.len") <|
  .cons (.prim "<") <|
  .cons (.roll 3) <|
  .cons .quote <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.pick 2) <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.pick 2) <|
    .cons (.roll 3) <|
    .cons (.pick 3) <|
    .cons (.prim "seq-bool.at") <|
    .cons (.pick 2) <|
    .cons .quote <|
    .cons (.quotation (
      .cons (.lit (.int 1)) <|
      .cons (.prim "+") <|
      .empty)) <|
    .cons .compose <|
    .cons (.roll 3) <|
    .cons .quote <|
    .cons (.quotation (.empty)) <|
    .cons .compose <|
    .cons .ifThenElse <|
    .cons (.roll 2) <|
    .cons (.lit (.int 1)) <|
    .cons (.prim "+") <|
    .cons (.word "count-from") <|
    .empty)) <|
  .cons .compose <|
  .cons (.roll 2) <|
  .cons .quote <|
  .cons (.quotation (.empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `count-from`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "a9d668929520be7f7082380f346b62f392651d2af84ad81b41152c2667a2f1cb"

/-- The erased word type the image records for `count-from`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqBool^many,v1:Int^many,v2:Int^many--ρ,v0:Int^many)"

end «count-from»

namespace «count»

/-- The erased kernel program of `count`. -/
def body : Program :=
  .cons (.lit (.int 0)) <|
  .cons (.lit (.int 0)) <|
  .cons (.word "count-from") <|
  .empty

/-- The image's `body_digest` for `count`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "6e969eaaa75a3b3f4d96c12a1a8abc04600aed7ee8845c204ae7e2ae0f555d90"

/-- The erased word type the image records for `count`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqBool^many--ρ,v0:Int^many)"

end «count»

namespace «literal-sum»

/-- The erased kernel program of `literal-sum`. -/
def body : Program :=
  .cons (.lit (.intSeq [10, 20, 30])) <|
  .cons (.word "sum") <|
  .empty

/-- The image's `body_digest` for `literal-sum`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "86da74cfaba60da5bed303d411c6098733ff7582ec5c664d0ec6f48b8476a642"

/-- The erased word type the image records for `literal-sum`. -/
def erasedType : String := "(forallρ;ρ--ρ,v0:Int^many)"

end «literal-sum»

namespace «literal-mask»

/-- The erased kernel program of `literal-mask`. -/
def body : Program :=
  .cons (.lit (.boolSeq [true, false, true])) <|
  .cons (.lit (.bool true)) <|
  .cons (.prim "seq-bool.push") <|
  .empty

/-- The image's `body_digest` for `literal-mask`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "e941351b7d1f56982059b5503435149c1b641b3c7cbb0a500ea69d196762e4be"

/-- The erased word type the image records for `literal-mask`. -/
def erasedType : String := "(forallρ;ρ--ρ,v0:SeqBool^many)"

end «literal-mask»

namespace «third»

/-- The erased kernel program of `third`. -/
def body : Program :=
  .cons (.lit (.int 2)) <|
  .cons (.prim "seq-int.at") <|
  .empty

/-- The image's `body_digest` for `third`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "a2d47cb99fa6300ea83c554f353fcae92974c61600a9e480d91babfa37b1b15e"

/-- The erased word type the image records for `third`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many--ρ,v0:Int^many)"

end «third»

namespace «element»

/-- The erased kernel program of `element`. -/
def body : Program :=
  .cons (.prim "seq-int.at") <|
  .empty

/-- The image's `body_digest` for `element`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "658d32bb23b4572c5ac91a1dbc119a50e0f71b63d2cc779619b02ee3abd6a5bc"

/-- The erased word type the image records for `element`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many--ρ,v0:Int^many)"

end «element»

/-- Every word, in declaration order: its name, body, body digest and erased
type. -/
def words : List (String × Program × String × String) := [
  ("sum-from", «sum-from».body, «sum-from».bodyDigest, «sum-from».erasedType),
  ("sum", «sum».body, «sum».bodyDigest, «sum».erasedType),
  ("range-from", «range-from».body, «range-from».bodyDigest, «range-from».erasedType),
  ("range", «range».body, «range».bodyDigest, «range».erasedType),
  ("count-from", «count-from».body, «count-from».bodyDigest, «count-from».erasedType),
  ("count", «count».body, «count».bodyDigest, «count».erasedType),
  ("literal-sum", «literal-sum».body, «literal-sum».bodyDigest, «literal-sum».erasedType),
  ("literal-mask", «literal-mask».body, «literal-mask».bodyDigest, «literal-mask».erasedType),
  ("third", «third».body, «third».bodyDigest, «third».erasedType),
  ("element", «element».body, «element».bodyDigest, «element».erasedType)]

/-- The dictionary the reference runner builds for this source. -/
def dictionary : Dictionary
  | "sum-from" => some { type := adapterWordType, body := «sum-from».body }
  | "sum" => some { type := adapterWordType, body := «sum».body }
  | "range-from" => some { type := adapterWordType, body := «range-from».body }
  | "range" => some { type := adapterWordType, body := «range».body }
  | "count-from" => some { type := adapterWordType, body := «count-from».body }
  | "count" => some { type := adapterWordType, body := «count».body }
  | "literal-sum" => some { type := adapterWordType, body := «literal-sum».body }
  | "literal-mask" => some { type := adapterWordType, body := «literal-mask».body }
  | "third" => some { type := adapterWordType, body := «third».body }
  | "element" => some { type := adapterWordType, body := «element».body }
  | _ => none

/-! Each word's dictionary entry, which a proof unfolding a call to it needs. -/

theorem «sum-from».entry :
    dictionary "sum-from" = some { type := adapterWordType, body := «sum-from».body } := rfl

theorem «sum».entry :
    dictionary "sum" = some { type := adapterWordType, body := «sum».body } := rfl

theorem «range-from».entry :
    dictionary "range-from" = some { type := adapterWordType, body := «range-from».body } := rfl

theorem «range».entry :
    dictionary "range" = some { type := adapterWordType, body := «range».body } := rfl

theorem «count-from».entry :
    dictionary "count-from" = some { type := adapterWordType, body := «count-from».body } := rfl

theorem «count».entry :
    dictionary "count" = some { type := adapterWordType, body := «count».body } := rfl

theorem «literal-sum».entry :
    dictionary "literal-sum" = some { type := adapterWordType, body := «literal-sum».body } := rfl

theorem «literal-mask».entry :
    dictionary "literal-mask" = some { type := adapterWordType, body := «literal-mask».body } := rfl

theorem «third».entry :
    dictionary "third" = some { type := adapterWordType, body := «third».body } := rfl

theorem «element».entry :
    dictionary "element" = some { type := adapterWordType, body := «element».body } := rfl

end Firth.Exports.Programs.Sequences
