import FirthReferenceRun

/-!
Generated by `lake exe firthExportLean` from `examples/programs/signed.firth`. Do not edit:
`python3 tools/loop/update_kernel_exports.py` regenerates it, and CI fails when
this file differs from what the elaborator produces from that source.

Each word's `body` is the erased kernel program the elaborator checked and the
compiler admitted, and `bodyDigest` is the `body_digest` of that program in the
VM image. `FirthExportsTest` lowers every `body` again and fails unless it
hashes to `bodyDigest`.

`dictionary`, `Firth.ReferenceRun.adapterGamma` and `defaultCosts` are exactly
what the reference runner executes these words with.
-/

namespace Firth.Exports.Programs.Signed
open Firth.Interpreter
open Firth.ReferenceRun

/-- SHA-256 of the source text these definitions were generated from. -/
def sourceDigest : String := "7e6fc535d3a10e9c5a5f82aecbeec100d30d29b9100a36791ebb147cf263eeac"

namespace «diff»

/-- The erased kernel program of `diff`. -/
def body : Program :=
  .cons (.prim "-") <|
  .empty

/-- The image's `body_digest` for `diff`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "96389084750a38b4acf822d75bb2f2af4e3890931bffceee2a79a5a9e6ebb3fd"

/-- The erased word type the image records for `diff`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many)"

end «diff»

namespace «abs»

/-- The erased kernel program of `abs`. -/
def body : Program :=
  .cons .dup <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "<") <|
  .cons (.quotation (
    .cons .dup <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons (.quotation (
    .cons (.lit (.int 0)) <|
    .cons .swap <|
    .cons (.prim "-") <|
    .empty)) <|
  .cons .compose <|
  .cons (.quotation (
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons (.quotation (.empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `abs`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "ca78727ee88de0b4b06b01117bd70d4f04564a446a0ca810ba1342ef83f7bfd1"

/-- The erased word type the image records for `abs`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many--ρ,v0:Int^many)"

end «abs»

namespace «minimum-from»

/-- The erased kernel program of `minimum-from`. -/
def body : Program :=
  .cons .dup <|
  .cons (.quotation (
    .cons (.quotation (
      .cons (.quotation (
        .cons .dup <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .empty)) <|
  .cons .dip <|
  .cons (.quotation (
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons (.prim "seq-int.len") <|
  .cons (.prim "<") <|
  .cons (.quotation (
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons (.quotation (
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.quotation (
      .cons .dup <|
      .empty)) <|
    .cons .dip <|
    .empty)) <|
  .cons .dip <|
  .cons (.quotation (
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons .compose <|
  .cons (.quotation (
    .cons (.quotation (
      .cons (.quotation (
        .cons .dup <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons (.quotation (
      .cons (.quotation (
        .cons (.quotation (
          .cons .dup <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons (.quotation (
      .cons (.quotation (
        .cons (.quotation (
          .cons .dup <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons (.prim "seq-int.at") <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .dup <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons (.prim "<") <|
    .cons (.quotation (
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons (.quotation (
      .cons (.quotation (
        .cons (.quotation (
          .cons (.quotation (
            .cons .dup <|
            .empty)) <|
          .cons .dip <|
          .empty)) <|
        .cons .dip <|
        .empty)) <|
      .cons .dip <|
      .empty)) <|
    .cons .dip <|
    .cons (.quotation (
      .cons (.quotation (
        .cons (.quotation (
          .cons .swap <|
          .empty)) <|
        .cons .dip <|
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons .compose <|
    .cons (.quotation (
      .cons .swap <|
      .cons .swap <|
      .cons (.prim "seq-int.at") <|
      .empty)) <|
    .cons .compose <|
    .cons (.quotation (
      .cons (.quotation (
        .cons .swap <|
        .empty)) <|
      .cons .dip <|
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons .quote <|
    .cons (.quotation (.empty)) <|
    .cons .compose <|
    .cons .ifThenElse <|
    .cons (.quotation (
      .cons .swap <|
      .empty)) <|
    .cons .dip <|
    .cons .swap <|
    .cons (.lit (.int 1)) <|
    .cons (.prim "+") <|
    .cons (.word "minimum-from") <|
    .empty)) <|
  .cons .compose <|
  .cons (.quotation (
    .cons .swap <|
    .empty)) <|
  .cons .dip <|
  .cons .swap <|
  .cons .quote <|
  .cons (.quotation (.empty)) <|
  .cons .compose <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `minimum-from`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "86dc70ffd94efbdd32f352d0560f17cb0d0f1034a7553aabc28d7eace50e377a"

/-- The erased word type the image records for `minimum-from`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many,v2:Int^many--ρ,v0:Int^many)"

end «minimum-from»

namespace «minimum»

/-- The erased kernel program of `minimum`. -/
def body : Program :=
  .cons .dup <|
  .cons .swap <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "seq-int.at") <|
  .cons (.lit (.int 1)) <|
  .cons (.word "minimum-from") <|
  .empty

/-- The image's `body_digest` for `minimum`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "43a65aee257e662204d7ce5823d465bbf66f1b03175268756bfed855dbb6673b"

/-- The erased word type the image records for `minimum`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many--ρ,v0:Int^many)"

end «minimum»

namespace «offsets»

/-- The erased kernel program of `offsets`. -/
def body : Program :=
  .cons (.lit (.intSeq [(-3), 0, 5])) <|
  .cons (.lit (.int (-7))) <|
  .cons (.prim "seq-int.push") <|
  .empty

/-- The image's `body_digest` for `offsets`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "5206bd6752b158fcc24cfab20c62f5cb8c18dd53bcd642b2cee9a9b25e0cd69a"

/-- The erased word type the image records for `offsets`. -/
def erasedType : String := "(forallρ;ρ--ρ,v0:SeqInt^many)"

end «offsets»

namespace «element»

/-- The erased kernel program of `element`. -/
def body : Program :=
  .cons (.prim "seq-int.at") <|
  .empty

/-- The image's `body_digest` for `element`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "658d32bb23b4572c5ac91a1dbc119a50e0f71b63d2cc779619b02ee3abd6a5bc"

/-- The erased word type the image records for `element`. -/
def erasedType : String := "(forallρ;ρ,v0:SeqInt^many,v1:Int^many--ρ,v0:Int^many)"

end «element»

/-- Every word, in declaration order: its name, body and body digest. -/
def words : List (String × Program × String) := [
  ("diff", «diff».body, «diff».bodyDigest),
  ("abs", «abs».body, «abs».bodyDigest),
  ("minimum-from", «minimum-from».body, «minimum-from».bodyDigest),
  ("minimum", «minimum».body, «minimum».bodyDigest),
  ("offsets", «offsets».body, «offsets».bodyDigest),
  ("element", «element».body, «element».bodyDigest)]

/-- The dictionary the reference runner builds for this source. -/
def dictionary : Dictionary
  | "diff" => some { type := adapterWordType, body := «diff».body }
  | "abs" => some { type := adapterWordType, body := «abs».body }
  | "minimum-from" => some { type := adapterWordType, body := «minimum-from».body }
  | "minimum" => some { type := adapterWordType, body := «minimum».body }
  | "offsets" => some { type := adapterWordType, body := «offsets».body }
  | "element" => some { type := adapterWordType, body := «element».body }
  | _ => none

end Firth.Exports.Programs.Signed
