import FirthReferenceRun

/-!
Generated by `lake exe firthExportLean` from `examples/programs/sum-to.firth`. Do not edit:
`python3 tools/loop/update_kernel_exports.py` regenerates it, and CI fails when
this file differs from what the elaborator produces from that source.

Each word's `body` is the erased kernel program the elaborator checked and the
compiler accepted, and `bodyDigest` is the `body_digest` of that program in the
VM image. `FirthExportsTest` lowers every `body` again and fails unless it
hashes to `bodyDigest`.

`dictionary`, `Firth.ReferenceRun.adapterGamma` and `defaultCosts` are exactly
what the reference runner executes these words with.
-/

namespace Firth.Exports.Programs.SumTo
open Firth.Interpreter
open Firth.ReferenceRun

/-- SHA-256 of the source text these definitions were generated from. -/
def sourceDigest : String := "5a3dcdb9cbd2ee209f75061f26d898247b2257c151e15a3e31a89afb1b9dd788"

namespace «sum-to»

/-- The erased kernel program of `sum-to`. -/
def body : Program :=
  .cons (.lit (.int 0)) <|
  .cons .swap <|
  .cons (.word "sum-acc") <|
  .empty

/-- The image's `body_digest` for `sum-to`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "ef719ea2f5c0dfd9cdd6a21149a833aa34431bb0b50f87d378e5eecfe439d6dc"

/-- The erased word type the image records for `sum-to`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many--ρ,v0:Int^many)"

end «sum-to»

namespace «sum-acc»

/-- The erased kernel program of `sum-acc`. -/
def body : Program :=
  .cons .dup <|
  .cons (.lit (.int 0)) <|
  .cons (.prim "=") <|
  .cons (.quotation (
    .cons .drop <|
    .empty)) <|
  .cons (.quotation (
    .cons .dup <|
    .cons (.lit (.int 1)) <|
    .cons (.prim "-") <|
    .cons (.quotation (
      .cons (.prim "+") <|
      .empty)) <|
    .cons .dip <|
    .cons (.word "sum-acc") <|
    .empty)) <|
  .cons .ifThenElse <|
  .empty

/-- The image's `body_digest` for `sum-acc`: SHA-256 of `body` lowered to
target code, hex encoded. -/
def bodyDigest : String := "6eca79a71d906194ae54383cdb1c0e704fc1b143f937f564241c0f0461ddfc95"

/-- The erased word type the image records for `sum-acc`. -/
def erasedType : String := "(forallρ;ρ,v0:Int^many,v1:Int^many--ρ,v0:Int^many)"

end «sum-acc»

/-- Every word, in declaration order: its name, body, body digest and erased
type. -/
def words : List (String × Program × String × String) := [
  ("sum-to", «sum-to».body, «sum-to».bodyDigest, «sum-to».erasedType),
  ("sum-acc", «sum-acc».body, «sum-acc».bodyDigest, «sum-acc».erasedType)]

/-- The dictionary the reference runner builds for this source. -/
def dictionary : Dictionary
  | "sum-to" => some { type := adapterWordType, body := «sum-to».body }
  | "sum-acc" => some { type := adapterWordType, body := «sum-acc».body }
  | _ => none

/-! Each word's dictionary entry, which a proof unfolding a call to it needs. -/

theorem «sum-to».entry :
    dictionary "sum-to" = some { type := adapterWordType, body := «sum-to».body } := rfl

theorem «sum-acc».entry :
    dictionary "sum-acc" = some { type := adapterWordType, body := «sum-acc».body } := rfl

end Firth.Exports.Programs.SumTo
